import { lazy } from 'react';


// Lazy load all lab components
const labComponents: Record<string, React.LazyExoticComponent<React.ComponentType<any>>> = {
  // Class 8 Computer
  LabDataComm: lazy(() => import('../components/LabDataComm')),
  LabNetworkDevices: lazy(() => import('../components/LabNetworkDevices')),
  LabCricketSpreadsheet: lazy(() => import('../components/LabCricketSpreadsheet')),
  LabDataWorksheets: lazy(() => import('../components/LabDataWorksheets')),
  LabPseudocodeInterpreter: lazy(() => import('../components/LabPseudocodeInterpreter')),
  LabDiceGameAlgorithm: lazy(() => import('../components/LabDiceGameAlgorithm')),
  LabScratchMaze: lazy(() => import('../components/LabScratchMaze')),
  LabCyberScout: lazy(() => import('../components/LabCyberScout')),
  LabAntivirus: lazy(() => import('../components/LabAntivirus')),
  LabBusinessPlan: lazy(() => import('../components/LabBusinessPlan')),
  LabDigitalMarketing: lazy(() => import('../components/LabDigitalMarketing')),

  // Class 7 Computer
  LabC7Hardware: lazy(() => import('../components/LabC7Hardware')),
  LabC7EmergingTech: lazy(() => import('../components/LabC7EmergingTech')),
  LabC7Generations: lazy(() => import('../components/LabC7Generations')),
  LabC7NetworkDiagram: lazy(() => import('../components/LabC7NetworkDiagram')),
  LabC7UrduTyping: lazy(() => import('../components/LabC7UrduTyping')),
  LabC7LetterFormat: lazy(() => import('../components/LabC7LetterFormat')),
  LabC7CVCreation: lazy(() => import('../components/LabC7CVCreation')),
  LabC7IllustratedStory: lazy(() => import('../components/LabC7IllustratedStory')),
  LabC7PowerPointGeometry: lazy(() => import('../components/LabC7PowerPointGeometry')),
  LabC7WondersResearch: lazy(() => import('../components/LabC7WondersResearch')),
  LabC7ConditionalLogic: lazy(() => import('../components/LabC7ConditionalLogic')),
  LabC7GradingFlowchart: lazy(() => import('../components/LabC7GradingFlowchart')),
  LabC7ReverseFlowchart: lazy(() => import('../components/LabC7ReverseFlowchart')),
  LabC7SpriteManipulation: lazy(() => import('../components/LabC7SpriteManipulation')),
  LabC7LoopAdjustments: lazy(() => import('../components/LabC7LoopAdjustments')),
  LabC7BouncingBall: lazy(() => import('../components/LabC7BouncingBall')),
  LabC7AnimatedDialogue: lazy(() => import('../components/LabC7AnimatedDialogue')),
  LabC7InteractivePiano: lazy(() => import('../components/LabC7InteractivePiano')),
  LabC7Cybercrime: lazy(() => import('../components/LabC7Cybercrime')),
  LabC7DevianceDiscussion: lazy(() => import('../components/LabC7DevianceDiscussion')),
  LabC7EthicsChart: lazy(() => import('../components/LabC7EthicsChart')),
  LabC7DesignPrototype: lazy(() => import('../components/LabC7DesignPrototype')),
  LabC7MothersDay: lazy(() => import('../components/LabC7MothersDay')),

  // Class 6 Computer
  LabC6HealthCampaign: lazy(() => import('../components/LabC6HealthCampaign')),
  LabC6HardwareCharts: lazy(() => import('../components/LabC6HardwareCharts')),
  LabC6LabRules: lazy(() => import('../components/LabC6LabRules')),
  LabC6GroupPresentations: lazy(() => import('../components/LabC6GroupPresentations')),
  LabC6SystemSoftware: lazy(() => import('../components/LabC6SystemSoftware')),
  LabC6FileManagement1: lazy(() => import('../components/LabC6FileManagement1')),
  LabC6FileManagement2: lazy(() => import('../components/LabC6FileManagement2')),
  LabC6DietExercise: lazy(() => import('../components/LabC6DietExercise')),
  LabC6Paint3DFace: lazy(() => import('../components/LabC6Paint3DFace')),
  LabC6SolarSystem: lazy(() => import('../components/LabC6SolarSystem')),
  LabC6ProblemDecomposition: lazy(() => import('../components/LabC6ProblemDecomposition')),
  LabC6RoadSafetyProcess: lazy(() => import('../components/LabC6RoadSafetyProcess')),
  LabC6CoordinateExp: lazy(() => import('../components/LabC6CoordinateExp')),
  LabC6CostumeChange: lazy(() => import('../components/LabC6CostumeChange')),
  LabC6MovementTracking: lazy(() => import('../components/LabC6MovementTracking')),
  LabC6LoopAdjustments: lazy(() => import('../components/LabC6LoopAdjustments')),
  LabC6EthicsChart: lazy(() => import('../components/LabC6EthicsChart')),
  LabC6CyberScout: lazy(() => import('../components/LabC6CyberScout')),
  LabC6PosterCompetition: lazy(() => import('../components/LabC6PosterCompetition')),
  LabC6HobbyMonetization: lazy(() => import('../components/LabC6HobbyMonetization')),

  // Class 8 Science
  LabS8GreenhouseEffect: lazy(() => import('../components/LabS8GreenhouseEffect')),
  LabS8StimulusResponse: lazy(() => import('../components/LabS8StimulusResponse')),
  LabS8KneeJerk: lazy(() => import('../components/LabS8KneeJerk')),
  LabS8ReflexTime: lazy(() => import('../components/LabS8ReflexTime')),
  LabS8DNAExtraction: lazy(() => import('../components/LabS8DNAExtraction')),
  LabS8HumanVariations: lazy(() => import('../components/LabS8HumanVariations')),
  LabS8CrossingOver: lazy(() => import('../components/LabS8CrossingOver')),
  LabS8MakingYogurt: lazy(() => import('../components/LabS8MakingYogurt')),
  LabS8PeriodicTable: lazy(() => import('../components/LabS8PeriodicTable')),
  LabS8ElectronicConfig: lazy(() => import('../components/LabS8ElectronicConfig')),
  LabS8Malleability: lazy(() => import('../components/LabS8Malleability')),
  LabS8Flexibility: lazy(() => import('../components/LabS8Flexibility')),
  LabS8Density: lazy(() => import('../components/LabS8Density')),
  LabS8ThermalConductivity: lazy(() => import('../components/LabS8ThermalConductivity')),
  LabS8Sonorous: lazy(() => import('../components/LabS8Sonorous')),
  LabS8ChemicalReactionSigns: lazy(() => import('../components/LabS8ChemicalReactionSigns')),
  LabS8ConservationMass: lazy(() => import('../components/LabS8ConservationMass')),
  LabS8Endothermic: lazy(() => import('../components/LabS8Endothermic')),
  LabS8Exothermic: lazy(() => import('../components/LabS8Exothermic')),
  LabS8AcidLitmus: lazy(() => import('../components/LabS8AcidLitmus')),
  LabS8AlkaliLitmus: lazy(() => import('../components/LabS8AlkaliLitmus')),
  LabS8Neutralization: lazy(() => import('../components/LabS8Neutralization')),
  LabS8DeterminingPH: lazy(() => import('../components/LabS8DeterminingPH')),
  LabS8NailPressure: lazy(() => import('../components/LabS8NailPressure')),
  LabS8HydraulicElevator: lazy(() => import('../components/LabS8HydraulicElevator')),
  LabS8WaterRocket: lazy(() => import('../components/LabS8WaterRocket')),
  LabS8LaserMaze: lazy(() => import('../components/LabS8LaserMaze')),
  LabS8Periscope: lazy(() => import('../components/LabS8Periscope')),
  LabS8RefractionPencil: lazy(() => import('../components/LabS8RefractionPencil')),
  LabS8ConcaveMirror: lazy(() => import('../components/LabS8ConcaveMirror')),
  LabS8ConvexMirror: lazy(() => import('../components/LabS8ConvexMirror')),
  LabS8Electromagnet: lazy(() => import('../components/LabS8Electromagnet')),
  LabS8Toothpaste: lazy(() => import('../components/LabS8Toothpaste')),
  LabS8SoapMaking: lazy(() => import('../components/LabS8SoapMaking')),
  LabS8MilkPlastic: lazy(() => import('../components/LabS8MilkPlastic')),
  LabS8Detergent: lazy(() => import('../components/LabS8Detergent')),
  LabS8SolarCooker: lazy(() => import('../components/LabS8SolarCooker')),
  LabS8WindTurbine: lazy(() => import('../components/LabS8WindTurbine')),
  LabS8ChemicalCar: lazy(() => import('../components/LabS8ChemicalCar')),
  LabS8Windsock: lazy(() => import('../components/LabS8Windsock')),
  LabS8SkyMap: lazy(() => import('../components/LabS8SkyMap')),

  // Class 7 Science
  LabS7XylemTransport: lazy(() => import('../components/LabS7XylemTransport')),
  LabS7TranspirationObservation: lazy(() => import('../components/LabS7TranspirationObservation')),
  LabS7TranspirationLeaves: lazy(() => import('../components/LabS7TranspirationLeaves')),
  LabS7MineralsPlantGrowth: lazy(() => import('../components/LabS7MineralsPlantGrowth')),
  LabS7Unit1Projects: lazy(() => import('../components/LabS7Unit1Projects')),
  LabS7MeasuringLungCapacity: lazy(() => import('../components/LabS7MeasuringLungCapacity')),
  LabS7PulseRateExercise: lazy(() => import('../components/LabS7PulseRateExercise')),
  LabS7Unit2Projects: lazy(() => import('../components/LabS7Unit2Projects')),
  LabS7ImmuneSystemRolePlay: lazy(() => import('../components/LabS7ImmuneSystemRolePlay')),
  LabS7Unit3Projects: lazy(() => import('../components/LabS7Unit3Projects')),
  LabS7ChemicalChange: lazy(() => import('../components/LabS7ChemicalChange')),
  LabS7ThermalConduction: lazy(() => import('../components/LabS7ThermalConduction')),
  LabS7Unit4Projects: lazy(() => import('../components/LabS7Unit4Projects')),
  LabS7CalculatingSubatomicParticles: lazy(() => import('../components/LabS7CalculatingSubatomicParticles')),
  LabS7AtomModel: lazy(() => import('../components/LabS7AtomModel')),
  LabS7LithiumBonding: lazy(() => import('../components/LabS7LithiumBonding')),
  LabS7DiluteConcentratedSolutions: lazy(() => import('../components/LabS7DiluteConcentratedSolutions')),
  LabS7CleaningCoins: lazy(() => import('../components/LabS7CleaningCoins')),
  LabS7MakingRockCandy: lazy(() => import('../components/LabS7MakingRockCandy')),
  LabS7OilPollutants: lazy(() => import('../components/LabS7OilPollutants')),
  LabS7BalloonRocket: lazy(() => import('../components/LabS7BalloonRocket')),
  LabS7Unit8Projects: lazy(() => import('../components/LabS7Unit8Projects')),
  LabS7VibratingLengthPitch: lazy(() => import('../components/LabS7VibratingLengthPitch')),
  LabS7Unit9Projects: lazy(() => import('../components/LabS7Unit9Projects')),
  LabS7Unit10Projects: lazy(() => import('../components/LabS7Unit10Projects')),
  LabS7DripIrrigation: lazy(() => import('../components/LabS7DripIrrigation')),
  LabS7MakeStethoscope: lazy(() => import('../components/LabS7MakeStethoscope')),
  LabS7HandSanitizer: lazy(() => import('../components/LabS7HandSanitizer')),
  LabS7Unit11Projects: lazy(() => import('../components/LabS7Unit11Projects')),
  LabS7EarthSeasons: lazy(() => import('../components/LabS7EarthSeasons')),

  // Class 10 Physics
  LabP10ThermionicEmission: lazy(() => import('../components/LabP10ThermionicEmission')),
  LabP10LogicGates: lazy(() => import('../components/LabP10LogicGates')),
  LabP10RadioTransmission: lazy(() => import('../components/LabP10RadioTransmission')),
  LabP10OpticalFibers: lazy(() => import('../components/LabP10OpticalFibers')),
  LabP10Radioactivity: lazy(() => import('../components/LabP10Radioactivity')),
  LabP10HalfLife: lazy(() => import('../components/LabP10HalfLife')),
  LabP10ElectrostaticCharges: lazy(() => import('../components/LabP10ElectrostaticCharges')),
  LabP10Electroscope: lazy(() => import('../components/LabP10Electroscope')),
  LabP10OhmLaw: lazy(() => import('../components/LabP10OhmLaw')),
  LabP10SeriesCircuit: lazy(() => import('../components/LabP10SeriesCircuit')),
  LabP10ParallelCircuit: lazy(() => import('../components/LabP10ParallelCircuit')),
  LabP10MagneticField: lazy(() => import('../components/LabP10MagneticField')),
  LabP10ElectromagnetDC: lazy(() => import('../components/LabP10ElectromagnetDC')),
  LabP10FaradayLaw: lazy(() => import('../components/LabP10FaradayLaw')),
  LabP10WaveMotion: lazy(() => import('../components/LabP10WaveMotion')),
  LabP10RippleTank: lazy(() => import('../components/LabP10RippleTank')),
  LabP10RefractionIllusion: lazy(() => import('../components/LabP10RefractionIllusion')),
  LabP10SoundProduction: lazy(() => import('../components/LabP10SoundProduction')),
  LabP10SoundMedium: lazy(() => import('../components/LabP10SoundMedium')),
  LabP10StringTelephone: lazy(() => import('../components/LabP10StringTelephone')),
  LabP10SpeakerProject: lazy(() => import('../components/LabP10SpeakerProject')),
  LabP10PlaneMirror: lazy(() => import('../components/LabP10PlaneMirror')),
  LabP10RefractionBlocks: lazy(() => import('../components/LabP10RefractionBlocks')),
  LabP10TotalInternalReflection: lazy(() => import('../components/LabP10TotalInternalReflection')),
  LabP10CarbonFootprint: lazy(() => import('../components/LabP10CarbonFootprint')),
  LabP10SpecificHeatMixture: lazy(() => import('../components/LabP10SpecificHeatMixture')),
  LabP10SpecificHeatElectrical: lazy(() => import('../components/LabP10SpecificHeatElectrical')),
  LabP10ThermalConduction: lazy(() => import('../components/LabP10ThermalConduction')),
  LabP10ConvectionCurrents: lazy(() => import('../components/LabP10ConvectionCurrents')),
  LabP10InsulatingMaterials: lazy(() => import('../components/LabP10InsulatingMaterials')),
  LabP10AbsorbersReflectors: lazy(() => import('../components/LabP10AbsorbersReflectors')),
  LabP10LeslieCube: lazy(() => import('../components/LabP10LeslieCube')),
  LabP10ThermalExpansionSolid: lazy(() => import('../components/LabP10ThermalExpansionSolid')),
  LabP10ExpansionLiquids: lazy(() => import('../components/LabP10ExpansionLiquids')),
  LabP10GasPressureBalloon: lazy(() => import('../components/LabP10GasPressureBalloon')),
  LabP10LatentHeat: lazy(() => import('../components/LabP10LatentHeat')),

  // Class 10 Chemistry
  LabC10DiluteSolution: lazy(() => import('../components/LabC10DiluteSolution')),
  LabC10StandardizationTitration: lazy(() => import('../components/LabC10StandardizationTitration')),
  LabC10SaltTitration: lazy(() => import('../components/LabC10SaltTitration')),
  LabC10SaltExcessMetal: lazy(() => import('../components/LabC10SaltExcessMetal')),
  LabC10SaltExcessBase: lazy(() => import('../components/LabC10SaltExcessBase')),
  LabC10SaltExcessCarbonate: lazy(() => import('../components/LabC10SaltExcessCarbonate')),
  LabC10MetalReactivity: lazy(() => import('../components/LabC10MetalReactivity')),
  LabC10SaturatedUnsaturated: lazy(() => import('../components/LabC10SaturatedUnsaturated')),
  LabC10AceticAcidMetal: lazy(() => import('../components/LabC10AceticAcidMetal')),
  LabC10AceticAcidCarbonate: lazy(() => import('../components/LabC10AceticAcidCarbonate')),
  LabC10DownsCell: lazy(() => import('../components/LabC10DownsCell')),
  LabC10MoltenLeadChloride: lazy(() => import('../components/LabC10MoltenLeadChloride')),
  LabC10AqueousElectrolysis: lazy(() => import('../components/LabC10AqueousElectrolysis')),
  LabC10CopperRefining: lazy(() => import('../components/LabC10CopperRefining')),
  LabC10Electroplating: lazy(() => import('../components/LabC10Electroplating')),
  LabC10DanielCell: lazy(() => import('../components/LabC10DanielCell')),
  LabC10FuelCell: lazy(() => import('../components/LabC10FuelCell')),
  LabC10SurfaceAreaRate: lazy(() => import('../components/LabC10SurfaceAreaRate')),
  LabC10ConcentrationRate: lazy(() => import('../components/LabC10ConcentrationRate')),
  LabC10Esterification: lazy(() => import('../components/LabC10Esterification')),
  LabC10EthanolFermentation: lazy(() => import('../components/LabC10EthanolFermentation')),
  LabC10EthanolHydration: lazy(() => import('../components/LabC10EthanolHydration')),
  LabC10AlcoholCombustion: lazy(() => import('../components/LabC10AlcoholCombustion')),
  LabC10AdditionPolymerisation: lazy(() => import('../components/LabC10AdditionPolymerisation')),
  LabC10CondensationPolymerisation: lazy(() => import('../components/LabC10CondensationPolymerisation')),
  LabC10PETAcidHydrolysis: lazy(() => import('../components/LabC10PETAcidHydrolysis')),
  LabC10BiochemicalTest: lazy(() => import('../components/LabC10BiochemicalTest')),

  // Class 10 Computer Science
  LabCS10NumberSystems: lazy(() => import('../components/LabCS10NumberSystems')),
  LabCS10HelloWorld: lazy(() => import('../components/LabCS10HelloWorld')),
  LabCS10ComputationalThinking: lazy(() => import('../components/LabCS10ComputationalThinking')),
  LabCS10HTMLCSS: lazy(() => import('../components/LabCS10HTMLCSS')),
  LabCS10JSAlgorithms: lazy(() => import('../components/LabCS10JSAlgorithms')),
  LabCS10DynamicList: lazy(() => import('../components/LabCS10DynamicList')),
  LabCS10DataVisualization: lazy(() => import('../components/LabCS10DataVisualization')),
  LabCS10ChurnPrediction: lazy(() => import('../components/LabCS10ChurnPrediction')),
  LabCS10FutureTech: lazy(() => import('../components/LabCS10FutureTech')),
  LabCS10CyberSafety: lazy(() => import('../components/LabCS10CyberSafety')),
  LabCS10DigitalMarketing: lazy(() => import('../components/LabCS10DigitalMarketing')),
  LabCS10MarketResearch: lazy(() => import('../components/LabCS10MarketResearch')),
  LabCS10Financials: lazy(() => import('../components/LabCS10Financials')),
  LabCS10BusinessPitch: lazy(() => import('../components/LabCS10BusinessPitch')),

  // Class 10 Mathematics
  LabM10Vectors: lazy(() => import('../components/LabM10Vectors')),
  LabM10ChordBisectors: lazy(() => import('../components/LabM10ChordBisectors')),
  LabM10EqualChords: lazy(() => import('../components/LabM10EqualChords')),
  LabM10TangentProperties: lazy(() => import('../components/LabM10TangentProperties')),
  LabM10CircleAngles: lazy(() => import('../components/LabM10CircleAngles')),
  LabM10CircleBasics: lazy(() => import('../components/LabM10CircleBasics')),
  LabM10TangentConstruction: lazy(() => import('../components/LabM10TangentConstruction')),
  LabM10CommonTangents: lazy(() => import('../components/LabM10CommonTangents')),
  LabM10StatisticsWheels: lazy(() => import('../components/LabM10StatisticsWheels')),
  LabM10ComplexApplications: lazy(() => import('../components/LabM10ComplexApplications')),
  LabM10QuadraticApplications: lazy(() => import('../components/LabM10QuadraticApplications')),
  LabM10MatrixApplications: lazy(() => import('../components/LabM10MatrixApplications')),
  LabM10InequalityApplications: lazy(() => import('../components/LabM10InequalityApplications')),
  LabM10FractionApplications: lazy(() => import('../components/LabM10FractionApplications')),
  LabM10FunctionApplications: lazy(() => import('../components/LabM10FunctionApplications')),
  LabM10VectorApplications: lazy(() => import('../components/LabM10VectorApplications')),
  LabM10TrigApplications: lazy(() => import('../components/LabM10TrigApplications')),
  LabM10CircleApplications: lazy(() => import('../components/LabM10CircleApplications')),
  LabM10StatsApplications: lazy(() => import('../components/LabM10StatsApplications')),

  // Class 10 Biology
  LabB10DigestiveSystem: lazy(() => import('../components/LabB10DigestiveSystem')),
  LabB10BloodSmear: lazy(() => import('../components/LabB10BloodSmear')),
  LabB10RespiratorySystem: lazy(() => import('../components/LabB10RespiratorySystem')),
  LabB10KidneyDissection: lazy(() => import('../components/LabB10KidneyDissection')),
  LabB10NervousSystem: lazy(() => import('../components/LabB10NervousSystem')),
  LabB10Genetics: lazy(() => import('../components/LabB10Genetics')),
  LabB10Biostatistics: lazy(() => import('../components/LabB10Biostatistics')),

  // Class 9 Biology
  LabB9Biodiversity: lazy(() => import('../components/LabB9Biodiversity')),
  LabB9Microscopy: lazy(() => import('../components/LabB9Microscopy')),
  LabB9Biochemistry: lazy(() => import('../components/LabB9Biochemistry')),
  LabB9Enzymes: lazy(() => import('../components/LabB9Enzymes')),
  LabB9PlantPhysiology: lazy(() => import('../components/LabB9PlantPhysiology')),
  LabB9PlantReproduction: lazy(() => import('../components/LabB9PlantReproduction')),

  // Class 9 Chemistry
  LabC9StatesOfMatter: lazy(() => import('../components/LabC9StatesOfMatter')),
  LabC9AtomicStructure: lazy(() => import('../components/LabC9AtomicStructure')),
  LabC9Electrochemistry: lazy(() => import('../components/LabC9Electrochemistry')),
  LabC9EnvironmentalChem: lazy(() => import('../components/LabC9EnvironmentalChem')),
  LabC9OrganicChem: lazy(() => import('../components/LabC9OrganicChem')),
  LabC9SeparationTech: lazy(() => import('../components/LabC9SeparationTech')),
  LabC9QualitativeAnalysis: lazy(() => import('../components/LabC9QualitativeAnalysis')),

  // Class 9 Physics
  LabP9MeasurementTools: lazy(() => import('../components/LabP9MeasurementTools')),
  LabP9VolumeDensity: lazy(() => import('../components/LabP9VolumeDensity')),
  LabP9Kinematics: lazy(() => import('../components/LabP9Kinematics')),
  LabP9Inertia: lazy(() => import('../components/LabP9Inertia')),
  LabP9Friction: lazy(() => import('../components/LabP9Friction')),
  LabP9Pressure: lazy(() => import('../components/LabP9Pressure')),
  LabP9Springs: lazy(() => import('../components/LabP9Springs')),
  LabP9MagnetismFields: lazy(() => import('../components/LabP9MagnetismFields')),
  LabP9MagnetismInduction: lazy(() => import('../components/LabP9MagnetismInduction')),
  LabP9EverydayPhysics: lazy(() => import('../components/LabP9EverydayPhysics')),

  // Class 9 Computer Science
  LabCS9ComputerSystems: lazy(() => import('../components/LabCS9ComputerSystems')),
  LabCS9Algorithms: lazy(() => import('../components/LabCS9Algorithms')),
  LabCS9WebBasics: lazy(() => import('../components/LabCS9WebBasics')),
  LabCS9JavaScript: lazy(() => import('../components/LabCS9JavaScript')),
  LabCS9WebProjects: lazy(() => import('../components/LabCS9WebProjects')),
  LabCS9DataAnalysis: lazy(() => import('../components/LabCS9DataAnalysis')),
  LabCS9AIApplications: lazy(() => import('../components/LabCS9AIApplications')),
  LabCS9CyberSafety: lazy(() => import('../components/LabCS9CyberSafety')),
  LabCS9Entrepreneurship: lazy(() => import('../components/LabCS9Entrepreneurship')),

  // Class 9 Mathematics
  LabM9RealNumbers: lazy(() => import('../components/LabM9RealNumbers')),
  LabM9Logarithms: lazy(() => import('../components/LabM9Logarithms')),
  LabM9SetsRelations: lazy(() => import('../components/LabM9SetsRelations')),
  LabM9AlgebraicManipulation: lazy(() => import('../components/LabM9AlgebraicManipulation')),
  LabM9Trigonometry: lazy(() => import('../components/LabM9Trigonometry')),
  LabM9CoordinateGeometry: lazy(() => import('../components/LabM9CoordinateGeometry')),
  LabM9LinearGraphs: lazy(() => import('../components/LabM9LinearGraphs')),
  LabM9GeometryPolygons: lazy(() => import('../components/LabM9GeometryPolygons')),
  LabM9BasicStatistics: lazy(() => import('../components/LabM9BasicStatistics')),

  // Class 11 Chemistry
  LabC11AtomicStructure: lazy(() => import('../components/LabC11AtomicStructure')),
  LabC11MolecularBonding: lazy(() => import('../components/LabC11MolecularBonding')),
  LabC11Stoichiometry: lazy(() => import('../components/LabC11Stoichiometry')),
  LabC11PhasesOfMatter: lazy(() => import('../components/LabC11PhasesOfMatter')),
  LabC11EnergeticsKinetics: lazy(() => import('../components/LabC11EnergeticsKinetics')),
  LabC11IndustrialEquilibrium: lazy(() => import('../components/LabC11IndustrialEquilibrium')),
  LabC11AcidsBases: lazy(() => import('../components/LabC11AcidsBases')),
  LabC11EnvironmentalChem: lazy(() => import('../components/LabC11EnvironmentalChem')),
  LabC11OrganicAnalysis: lazy(() => import('../components/LabC11OrganicAnalysis')),
  LabC11OrganicSynthesis: lazy(() => import('../components/LabC11OrganicSynthesis')),

  // Class 11 Physics
  LabP11PhysicalQuantities: lazy(() => import('../components/LabP11PhysicalQuantities')),
  LabP11Vectors: lazy(() => import('../components/LabP11Vectors')),
  LabP11TranslatoryMotion: lazy(() => import('../components/LabP11TranslatoryMotion')),
  LabP11RotationalMotion: lazy(() => import('../components/LabP11RotationalMotion')),
  LabP11WorkEnergy: lazy(() => import('../components/LabP11WorkEnergy')),
  LabP11FluidMechanics: lazy(() => import('../components/LabP11FluidMechanics')),
  LabP11Solids: lazy(() => import('../components/LabP11Solids')),
  LabP11Thermodynamics: lazy(() => import('../components/LabP11Thermodynamics')),
  LabP11Waves: lazy(() => import('../components/LabP11Waves')),
  LabP11Electrostatics: lazy(() => import('../components/LabP11Electrostatics')),
  LabP11Electricity: lazy(() => import('../components/LabP11Electricity')),
  LabP11Electromagnetism: lazy(() => import('../components/LabP11Electromagnetism')),
  LabP11ModernPhysics: lazy(() => import('../components/LabP11ModernPhysics')),

  // Class 11 Computer Science
  LabCS11SystemsNetworks: lazy(() => import('../components/LabCS11SystemsNetworks')),
  LabCS11Algorithms: lazy(() => import('../components/LabCS11Algorithms')),
  LabCS11Python: lazy(() => import('../components/LabCS11Python')),
  LabCS11DataScience: lazy(() => import('../components/LabCS11DataScience')),
  LabCS11Applications: lazy(() => import('../components/LabCS11Applications')),
  LabCS11Impacts: lazy(() => import('../components/LabCS11Impacts')),
  LabCS11Research: lazy(() => import('../components/LabCS11Research')),
  LabCS11ProductDev: lazy(() => import('../components/LabCS11ProductDev')),

  // Class 11 Biology
  LabB11Cytology: lazy(() => import('../components/LabB11Cytology')),
  LabB11Biomolecules: lazy(() => import('../components/LabB11Biomolecules')),
  LabB11Enzymes: lazy(() => import('../components/LabB11Enzymes')),
  LabB11Bioenergetics: lazy(() => import('../components/LabB11Bioenergetics')),
  LabB11Microbiology: lazy(() => import('../components/LabB11Microbiology')),
  LabB11Fungi: lazy(() => import('../components/LabB11Fungi')),
  LabB11PlantPhysiology: lazy(() => import('../components/LabB11PlantPhysiology')),
  LabB11Inheritance: lazy(() => import('../components/LabB11Inheritance')),
  LabB11Genetics: lazy(() => import('../components/LabB11Genetics')),

  // Class 12 Biology
  LabB12Digestive: lazy(() => import('../components/LabB12Digestive')),
  LabB12Cardiorespiratory: lazy(() => import('../components/LabB12Cardiorespiratory')),
  LabB12Urinary: lazy(() => import('../components/LabB12Urinary')),
  LabB12NeuroEndocrine: lazy(() => import('../components/LabB12NeuroEndocrine')),
  LabB12Skeletal: lazy(() => import('../components/LabB12Skeletal')),
  LabB12Immunity: lazy(() => import('../components/LabB12Immunity')),
  LabB12Biotechnology: lazy(() => import('../components/LabB12Biotechnology')),
  LabB12StructuralStats: lazy(() => import('../components/LabB12StructuralStats')),
  LabB12PharmacologyEcology: lazy(() => import('../components/LabB12PharmacologyEcology')),

  // Class 12 Physics
  LabP12Gravitation: lazy(() => import('../components/LabP12Gravitation')),
  LabP12ThermoMechanics: lazy(() => import('../components/LabP12ThermoMechanics')),
  LabP12SHM: lazy(() => import('../components/LabP12SHM')),
  LabP12Diffraction: lazy(() => import('../components/LabP12Diffraction')),
  LabP12ElectricPotential: lazy(() => import('../components/LabP12ElectricPotential')),
  LabP12AlternatingCurrent: lazy(() => import('../components/LabP12AlternatingCurrent')),
  LabP12QuantumNuclear: lazy(() => import('../components/LabP12QuantumNuclear')),
  LabP12CosmologyClimate: lazy(() => import('../components/LabP12CosmologyClimate')),
  LabP12MedicalImaging: lazy(() => import('../components/LabP12MedicalImaging')),

  // Class 12 Chemistry
  LabC12Electrochemistry: lazy(() => import('../components/LabC12Electrochemistry')),
  LabC12EquilibriumAcidBase: lazy(() => import('../components/LabC12EquilibriumAcidBase')),
  LabC12TransitionMetals: lazy(() => import('../components/LabC12TransitionMetals')),
  LabC12OrganicSynthesis: lazy(() => import('../components/LabC12OrganicSynthesis')),
  LabC12Biochemistry: lazy(() => import('../components/LabC12Biochemistry')),
  LabC12SpectroscopyChromatography: lazy(() => import('../components/LabC12SpectroscopyChromatography')),
  LabC12Medicine: lazy(() => import('../components/LabC12Medicine')),
  LabC12Agriculture: lazy(() => import('../components/LabC12Agriculture')),
  LabC12IndustryMaterials: lazy(() => import('../components/LabC12IndustryMaterials')),

  // Class 12 Computer Science
  LabCS12HCI: lazy(() => import('../components/LabCS12HCI')),
  LabCS12DataStructures: lazy(() => import('../components/LabCS12DataStructures')),
  LabCS12Programming: lazy(() => import('../components/LabCS12Programming')),
  LabCS12MachineLearning: lazy(() => import('../components/LabCS12MachineLearning')),
  LabCS12DeepLearning: lazy(() => import('../components/LabCS12DeepLearning')),
  LabCS12IoTCloud: lazy(() => import('../components/LabCS12IoTCloud')),
  LabCS12Cybersecurity: lazy(() => import('../components/LabCS12Cybersecurity')),
  LabCS12DigitalLiteracy: lazy(() => import('../components/LabCS12DigitalLiteracy')),
  LabCS12Entrepreneurship: lazy(() => import('../components/LabCS12Entrepreneurship')),

  // Class 11 Mathematics
  LabM11ComplexNumbers: lazy(() => import('../components/LabM11ComplexNumbers')),
  LabM11Matrices: lazy(() => import('../components/LabM11Matrices')),
  LabM11Vectors: lazy(() => import('../components/LabM11Vectors')),
  LabM11SequencesSeries: lazy(() => import('../components/LabM11SequencesSeries')),
  LabM11Polynomials: lazy(() => import('../components/LabM11Polynomials')),
  LabM11Trigonometry: lazy(() => import('../components/LabM11Trigonometry')),
  LabM11Permutations: lazy(() => import('../components/LabM11Permutations')),
  LabM11BinomialInduction: lazy(() => import('../components/LabM11BinomialInduction')),

  // Class 12 Mathematics
  LabM12Derivatives: lazy(() => import('../components/LabM12Derivatives')),
  LabM12Integration: lazy(() => import('../components/LabM12Integration')),
  LabM12DifferentialEq: lazy(() => import('../components/LabM12DifferentialEq')),
  LabM12Conics: lazy(() => import('../components/LabM12Conics')),
  LabM12AnalyticalGeometry: lazy(() => import('../components/LabM12AnalyticalGeometry')),
  LabM12Kinematics: lazy(() => import('../components/LabM12Kinematics')),
  LabM12Functions: lazy(() => import('../components/LabM12Functions')),
  LabM12InverseTrig: lazy(() => import('../components/LabM12InverseTrig')),

  // Class 6 Science
  LabS6Microscope: lazy(() => import('../components/LabS6Microscope')),
  LabS6Unit1Projects: lazy(() => import('../components/LabS6Unit1Projects')),
  LabS6VegetativePropagation: lazy(() => import('../components/LabS6VegetativePropagation')),
  LabS6FatDetection: lazy(() => import('../components/LabS6FatDetection')),
  LabS6BalancedDiet: lazy(() => import('../components/LabS6BalancedDiet')),
  LabS6DigestionMechanics: lazy(() => import('../components/LabS6DigestionMechanics')),
  LabS6AlimentaryCanal: lazy(() => import('../components/LabS6AlimentaryCanal')),
  LabS6LungModel: lazy(() => import('../components/LabS6LungModel')),
  LabS6ParticleSimulation: lazy(() => import('../components/LabS6ParticleSimulation')),
  LabS6MolecularBuilder: lazy(() => import('../components/LabS6MolecularBuilder')),
  LabS6ElementsCompounds: lazy(() => import('../components/LabS6ElementsCompounds')),
  LabS6Separation: lazy(() => import('../components/LabS6Separation')),
  LabS6SolutionInvestigation: lazy(() => import('../components/LabS6SolutionInvestigation')),
  LabS6EnergyTransformation: lazy(() => import('../components/LabS6EnergyTransformation')),
  LabS6EnergyProjects: lazy(() => import('../components/LabS6EnergyProjects')),
  LabS6CircuitBuilder: lazy(() => import('../components/LabS6CircuitBuilder')),
  LabS6ConductorsInsulators: lazy(() => import('../components/LabS6ConductorsInsulators')),
  LabS6Magnetism: lazy(() => import('../components/LabS6Magnetism')),
  LabS6PlantGrowth: lazy(() => import('../components/LabS6PlantGrowth')),
  LabS6SolarSystemBuilder: lazy(() => import('../components/LabS6SolarSystemBuilder')),
  LabS6EverydayTech: lazy(() => import('../components/LabS6EverydayTech')),

  // Class 8 Math
  LabM8RealEstimation: lazy(() => import('../components/LabM8RealEstimation')),
  LabM8RootsFinance: lazy(() => import('../components/LabM8RootsFinance')),
  LabM8SetsAlgebra: lazy(() => import('../components/LabM8SetsAlgebra')),
  LabM8EquationsInequalities: lazy(() => import('../components/LabM8EquationsInequalities')),
  LabM8Transformations: lazy(() => import('../components/LabM8Transformations')),
  LabM8GeometryTriangles: lazy(() => import('../components/LabM8GeometryTriangles')),
  LabM8Mensuration: lazy(() => import('../components/LabM8Mensuration')),
  LabM8DataProbability: lazy(() => import('../components/LabM8DataProbability')),

  // Class 6 English
  LabE6NounsPronouns: lazy(() => import('../components/LabE6NounsPronouns')),
  LabE6SentencesAffixes: lazy(() => import('../components/LabE6SentencesAffixes')),
  LabE6VerbsAdverbs: lazy(() => import('../components/LabE6VerbsAdverbs')),
  LabE6PrepositionsStructure: lazy(() => import('../components/LabE6PrepositionsStructure')),
  LabE6ClausesConjunctions: lazy(() => import('../components/LabE6ClausesConjunctions')),
  LabE6TensesPunctuation: lazy(() => import('../components/LabE6TensesPunctuation')),
  LabE6FiguresOfSpeech: lazy(() => import('../components/LabE6FiguresOfSpeech')),
  LabE6WritingMechanics: lazy(() => import('../components/LabE6WritingMechanics')),

  // Class 7 English
  LabE7ArticlesAdjectives: lazy(() => import('../components/LabE7ArticlesAdjectives')),
  LabE7FiguresOfSpeech: lazy(() => import('../components/LabE7FiguresOfSpeech')),
  LabE7PrepositionsModals: lazy(() => import('../components/LabE7PrepositionsModals')),
  LabE7VerbsCollocations: lazy(() => import('../components/LabE7VerbsCollocations')),
  LabE7Tenses: lazy(() => import('../components/LabE7Tenses')),
  LabE7Conjunctions: lazy(() => import('../components/LabE7Conjunctions')),
  LabE7PronounsClauses: lazy(() => import('../components/LabE7PronounsClauses')),
  LabE7VocabPunctuation: lazy(() => import('../components/LabE7VocabPunctuation')),

  // Class 8 English
  LabE8NounsPhonetics: lazy(() => import('../components/LabE8NounsPhonetics')),
  LabE8PronounsMorphology: lazy(() => import('../components/LabE8PronounsMorphology')),
  LabE8AdjectivesPoetry: lazy(() => import('../components/LabE8AdjectivesPoetry')),
  LabE8VerbsModals: lazy(() => import('../components/LabE8VerbsModals')),
  LabE8AdverbsPrepositions: lazy(() => import('../components/LabE8AdverbsPrepositions')),
  LabE8ConjunctionsClauses: lazy(() => import('../components/LabE8ConjunctionsClauses')),
  LabE8TensesVoice: lazy(() => import('../components/LabE8TensesVoice')),
  LabE8NarrationConditionals: lazy(() => import('../components/LabE8NarrationConditionals')),


  // Class 9 English
  LabE9PartsOfSpeech: lazy(() => import('../components/LabE9PartsOfSpeech')),
  LabE9Verbals: lazy(() => import('../components/LabE9Verbals')),
  LabE9TensesAgreement: lazy(() => import('../components/LabE9TensesAgreement')),
  LabE9Phrases: lazy(() => import('../components/LabE9Phrases')),
  LabE9PrepositionsConjunctions: lazy(() => import('../components/LabE9PrepositionsConjunctions')),
  LabE9SentenceStructure: lazy(() => import('../components/LabE9SentenceStructure')),
  LabE9Narration: lazy(() => import('../components/LabE9Narration')),
  LabE9PunctuationVocabulary: lazy(() => import('../components/LabE9PunctuationVocabulary')),

  // Class 10 English
  LabE10NounsPronouns: lazy(() => import('../components/LabE10NounsPronouns')),
  LabE10VerbsAdjectives: lazy(() => import('../components/LabE10VerbsAdjectives')),
  LabE10AdverbsPrepositions: lazy(() => import('../components/LabE10AdverbsPrepositions')),
  LabE10ConjunctionsTenses: lazy(() => import('../components/LabE10ConjunctionsTenses')),
  LabE10ModalsConditionals: lazy(() => import('../components/LabE10ModalsConditionals')),
  LabE10PhrasesClauses: lazy(() => import('../components/LabE10PhrasesClauses')),
  LabE10SentenceNarration: lazy(() => import('../components/LabE10SentenceNarration')),
  LabE10VocabularyStylistics: lazy(() => import('../components/LabE10VocabularyStylistics')),
  
  // Class 11 English
  LabE11NounsPronouns: lazy(() => import('../components/LabE11NounsPronouns')),
  LabE11AdjectivesAdverbs: lazy(() => import('../components/LabE11AdjectivesAdverbs')),
  LabE11PrepositionsConjunctions: lazy(() => import('../components/LabE11PrepositionsConjunctions')),
  LabE11VerbsModals: lazy(() => import('../components/LabE11VerbsModals')),
  LabE11TensesVerbals: lazy(() => import('../components/LabE11TensesVerbals')),
  LabE11PhrasesClauses: lazy(() => import('../components/LabE11PhrasesClauses')),
  LabE11SentenceStructure: lazy(() => import('../components/LabE11SentenceStructure')),
  LabE11VocabularyStylistics: lazy(() => import('../components/LabE11VocabularyStylistics')),

  // Class 12 English
  LabE12NounsPronouns: lazy(() => import('../components/LabE12NounsPronouns')),
  LabE12AdjectivesAdverbs: lazy(() => import('../components/LabE12AdjectivesAdverbs')),
  LabE12PrepositionsConjunctions: lazy(() => import('../components/LabE12PrepositionsConjunctions')),
  LabE12VerbsModals: lazy(() => import('../components/LabE12VerbsModals')),
  LabE12TensesVerbals: lazy(() => import('../components/LabE12TensesVerbals')),
  LabE12PhrasesClauses: lazy(() => import('../components/LabE12PhrasesClauses')),
  LabE12SentenceStructure: lazy(() => import('../components/LabE12SentenceStructure')),
  LabE12VocabularyStylistics: lazy(() => import('../components/LabE12VocabularyStylistics')),
};

// Module ID to component name mapping
const moduleIdToComponent: Record<string, string> = {
  // Class 8 Computer
  'c8c_1_1': 'LabDataComm',
  'c8c_1_2': 'LabNetworkDevices',
  'c8c_2_1': 'LabCricketSpreadsheet',
  'c8c_2_2': 'LabDataWorksheets',
  'c8c_3_1': 'LabPseudocodeInterpreter',
  'c8c_3_2': 'LabDiceGameAlgorithm',
  'c8c_4_1': 'LabScratchMaze',
  'c8c_5_1': 'LabCyberScout',
  'c8c_5_2': 'LabAntivirus',
  'c8c_6_1': 'LabBusinessPlan',
  'c8c_6_2': 'LabDigitalMarketing',

  // Class 7 Computer
  'c7c_1_1': 'LabC7Hardware',
  'c7c_1_2': 'LabC7EmergingTech',
  'c7c_1_3': 'LabC7Generations',
  'c7c_1_4': 'LabC7NetworkDiagram',
  'c7c_2_1': 'LabC7UrduTyping',
  'c7c_2_2': 'LabC7LetterFormat',
  'c7c_2_3': 'LabC7CVCreation',
  'c7c_2_4': 'LabC7IllustratedStory',
  'c7c_2_5': 'LabC7PowerPointGeometry',
  'c7c_2_6': 'LabC7WondersResearch',
  'c7c_3_1': 'LabC7ConditionalLogic',
  'c7c_3_2': 'LabC7GradingFlowchart',
  'c7c_3_3': 'LabC7ReverseFlowchart',
  'c7c_4_1': 'LabC7SpriteManipulation',
  'c7c_4_2': 'LabC7LoopAdjustments',
  'c7c_4_3': 'LabC7BouncingBall',
  'c7c_4_4': 'LabC7AnimatedDialogue',
  'c7c_4_5': 'LabC7InteractivePiano',
  'c7c_5_1': 'LabC7Cybercrime',
  'c7c_5_2': 'LabC7DevianceDiscussion',
  'c7c_5_3': 'LabC7EthicsChart',
  'c7c_6_1': 'LabC7DesignPrototype',
  'c7c_6_2': 'LabC7MothersDay',

  // Class 6 Computer
  'c6c_1_1': 'LabC6HealthCampaign',
  'c6c_1_2': 'LabC6HardwareCharts',
  'c6c_1_3': 'LabC6LabRules',
  'c6c_1_4': 'LabC6GroupPresentations',
  'c6c_2_1': 'LabC6SystemSoftware',
  'c6c_2_2': 'LabC6FileManagement1',
  'c6c_2_3': 'LabC6FileManagement2',
  'c6c_2_4': 'LabC6DietExercise',
  'c6c_2_5': 'LabC6Paint3DFace',
  'c6c_2_6': 'LabC6SolarSystem',
  'c6c_3_1': 'LabC6ProblemDecomposition',
  'c6c_3_2': 'LabC6RoadSafetyProcess',
  'c6c_4_1': 'LabC6CoordinateExp',
  'c6c_4_2': 'LabC6CostumeChange',
  'c6c_4_3': 'LabC6MovementTracking',
  'c6c_4_4': 'LabC6LoopAdjustments',
  'c6c_5_1': 'LabC6EthicsChart',
  'c6c_5_2': 'LabC6CyberScout',
  'c6c_5_3': 'LabC6PosterCompetition',
  'c6c_6_1': 'LabC6HobbyMonetization',

  // Class 8 Science
  'c8s_1_1': 'LabS8GreenhouseEffect',
  'c8s_2_1': 'LabS8StimulusResponse',
  'c8s_2_2': 'LabS8KneeJerk',
  'c8s_2_3': 'LabS8ReflexTime',
  'c8s_3_1': 'LabS8DNAExtraction',
  'c8s_3_2': 'LabS8HumanVariations',
  'c8s_3_3': 'LabS8CrossingOver',
  'c8s_4_1': 'LabS8MakingYogurt',
  'c8s_5_1': 'LabS8PeriodicTable',
  'c8s_5_2': 'LabS8ElectronicConfig',
  'c8s_5_3': 'LabS8Malleability',
  'c8s_5_4': 'LabS8Flexibility',
  'c8s_5_5': 'LabS8Density',
  'c8s_5_6': 'LabS8ThermalConductivity',
  'c8s_5_7': 'LabS8Sonorous',
  'c8s_6_1': 'LabS8ChemicalReactionSigns',
  'c8s_6_2': 'LabS8ConservationMass',
  'c8s_6_3': 'LabS8Endothermic',
  'c8s_6_4': 'LabS8Exothermic',
  'c8s_7_1': 'LabS8AcidLitmus',
  'c8s_7_2': 'LabS8AlkaliLitmus',
  'c8s_7_3': 'LabS8Neutralization',
  'c8s_7_4': 'LabS8DeterminingPH',
  'c8s_8_1': 'LabS8NailPressure',
  'c8s_8_2': 'LabS8HydraulicElevator',
  'c8s_8_3': 'LabS8WaterRocket',
  'c8s_9_1': 'LabS8LaserMaze',
  'c8s_9_3': 'LabS8Periscope',
  'c8s_9_4': 'LabS8RefractionPencil',
  'c8s_9_5': 'LabS8ConcaveMirror',
  'c8s_9_6': 'LabS8ConvexMirror',
  'c8s_10_1': 'LabS8Electromagnet',
  'c8s_11_1': 'LabS8Toothpaste',
  'c8s_11_2': 'LabS8SoapMaking',
  'c8s_11_3': 'LabS8MilkPlastic',
  'c8s_11_4': 'LabS8Detergent',
  'c8s_11_5': 'LabS8SolarCooker',
  'c8s_11_7': 'LabS8WindTurbine',
  'c8s_11_8': 'LabS8ChemicalCar',
  'c8s_11_9': 'LabS8Windsock',
  'c8s_12_1': 'LabS8SkyMap',

  // Class 7 Science
  'c7s_1_1': 'LabS7XylemTransport',
  'c7s_1_2': 'LabS7TranspirationObservation',
  'c7s_1_3': 'LabS7TranspirationLeaves',
  'c7s_1_4': 'LabS7MineralsPlantGrowth',
  'c7s_1_5': 'LabS7Unit1Projects',
  'c7s_2_1': 'LabS7MeasuringLungCapacity',
  'c7s_2_2': 'LabS7PulseRateExercise',
  'c7s_2_3': 'LabS7Unit2Projects',
  'c7s_3_1': 'LabS7ImmuneSystemRolePlay',
  'c7s_3_2': 'LabS7Unit3Projects',
  'c7s_4_1': 'LabS7ChemicalChange',
  'c7s_4_2': 'LabS7ThermalConduction',
  'c7s_4_3': 'LabS7Unit4Projects',
  'c7s_5_1': 'LabS7CalculatingSubatomicParticles',
  'c7s_5_2': 'LabS7AtomModel',
  'c7s_6_1': 'LabS7LithiumBonding',
  'c7s_7_1': 'LabS7DiluteConcentratedSolutions',
  'c7s_7_2': 'LabS7CleaningCoins',
  'c7s_7_3': 'LabS7MakingRockCandy',
  'c7s_7_4': 'LabS7OilPollutants',
  'c7s_8_1': 'LabS7BalloonRocket',
  'c7s_8_2': 'LabS7Unit8Projects',
  'c7s_9_1': 'LabS7VibratingLengthPitch',
  'c7s_9_2': 'LabS7Unit9Projects',
  'c7s_10_1': 'LabS7Unit10Projects',
  'c7s_11_1': 'LabS7DripIrrigation',
  'c7s_11_2': 'LabS7MakeStethoscope',
  'c7s_11_3': 'LabS7HandSanitizer',
  'c7s_11_4': 'LabS7Unit11Projects',
  'c7s_12_1': 'LabS7EarthSeasons',

  // Class 10 Physics
  'p10_10_1': 'LabP10CarbonFootprint',
  'p10_10_2': 'LabP10SpecificHeatMixture',
  'p10_10_3': 'LabP10SpecificHeatElectrical',
  'p10_10_4': 'LabP10ThermalConduction',
  'p10_10_5': 'LabP10ConvectionCurrents',
  'p10_10_6': 'LabP10InsulatingMaterials',
  'p10_10_7': 'LabP10AbsorbersReflectors',
  'p10_10_8': 'LabP10LeslieCube',
  'p10_11_1': 'LabP10ThermalExpansionSolid',
  'p10_11_2': 'LabP10ExpansionLiquids',
  'p10_11_3': 'LabP10GasPressureBalloon',
  'p10_11_4': 'LabP10LatentHeat',
  'p10_12_1': 'LabP10WaveMotion',
  'p10_12_2': 'LabP10RippleTank',
  'p10_12_3': 'LabP10RefractionIllusion',
  'p10_13_1': 'LabP10SoundProduction',
  'p10_13_2': 'LabP10SoundMedium',
  'p10_13_3': 'LabP10StringTelephone',
  'p10_13_4': 'LabP10SpeakerProject',
  'p10_14_1': 'LabP10PlaneMirror',
  'p10_14_2': 'LabP10RefractionBlocks',
  'p10_14_3': 'LabP10TotalInternalReflection',
  'p10_15_1': 'LabP10ElectrostaticCharges',
  'p10_15_2': 'LabP10Electroscope',
  'p10_16_1': 'LabP10OhmLaw',
  'p10_16_2': 'LabP10SeriesCircuit',
  'p10_16_3': 'LabP10ParallelCircuit',
  'p10_17_1': 'LabP10MagneticField',
  'p10_17_2': 'LabP10ElectromagnetDC',
  'p10_17_3': 'LabP10FaradayLaw',
  'p10_18_1': 'LabP10ThermionicEmission',
  'p10_18_2': 'LabP10LogicGates',
  'p10_19_1': 'LabP10RadioTransmission',
  'p10_19_2': 'LabP10OpticalFibers',
  'p10_20_1': 'LabP10Radioactivity',
  'p10_20_2': 'LabP10HalfLife',

  // Class 10 Chemistry
  'c10_3_1': 'LabC10DiluteSolution',
  'c10_3_2': 'LabC10StandardizationTitration',
  'c10_6_1': 'LabC10SaltTitration',
  'c10_6_2': 'LabC10SaltExcessMetal',
  'c10_6_3': 'LabC10SaltExcessBase',
  'c10_6_4': 'LabC10SaltExcessCarbonate',
  'c10_7_1': 'LabC10MetalReactivity',
  'c10_9_1': 'LabC10SaturatedUnsaturated',
  'c10_11_1': 'LabC10AceticAcidMetal',
  'c10_11_2': 'LabC10AceticAcidCarbonate',
  'c10_4_1': 'LabC10DownsCell',
  'c10_4_2': 'LabC10MoltenLeadChloride',
  'c10_4_3': 'LabC10AqueousElectrolysis',
  'c10_4_4': 'LabC10CopperRefining',
  'c10_4_5': 'LabC10Electroplating',
  'c10_4_6': 'LabC10DanielCell',
  'c10_4_7': 'LabC10FuelCell',
  'c10_5_1': 'LabC10SurfaceAreaRate',
  'c10_5_2': 'LabC10ConcentrationRate',
  'c10_8_1': 'LabC10Esterification',
  'c10_10_1': 'LabC10EthanolFermentation',
  'c10_10_2': 'LabC10EthanolHydration',
  'c10_12_1': 'LabC10AlcoholCombustion',
  'c10_13_1': 'LabC10AdditionPolymerisation',
  'c10_13_2': 'LabC10CondensationPolymerisation',
  'c10_14_1': 'LabC10PETAcidHydrolysis',
  'c10_15_1': 'LabC10BiochemicalTest',

  // Class 10 Computer Science
  'cs10_1_1': 'LabCS10NumberSystems',
  'cs10_1_2': 'LabCS10HelloWorld',
  'cs10_2_1': 'LabCS10ComputationalThinking',
  'cs10_3_1': 'LabCS10HTMLCSS',
  'cs10_4_1': 'LabCS10JSAlgorithms',
  'cs10_5_1': 'LabCS10DynamicList',
  'cs10_6_1': 'LabCS10DataVisualization',
  'cs10_7_1': 'LabCS10ChurnPrediction',
  'cs10_8_1': 'LabCS10FutureTech',
  'cs10_9_1': 'LabCS10CyberSafety',
  'cs10_10_1': 'LabCS10DigitalMarketing',
  'cs10_11_1': 'LabCS10MarketResearch',
  'cs10_12_1': 'LabCS10Financials',
  'cs10_13_1': 'LabCS10BusinessPitch',

  // Class 10 Mathematics
  'm10_1_1': 'LabM10Vectors',
  'm10_2_1': 'LabM10ChordBisectors',
  'm10_2_2': 'LabM10EqualChords',
  'm10_2_3': 'LabM10TangentProperties',
  'm10_3_1': 'LabM10CircleAngles',
  'm10_3_2': 'LabM10CircleBasics',
  'm10_3_3': 'LabM10TangentConstruction',
  'm10_3_4': 'LabM10CommonTangents',
  'm10_4_1': 'LabM10StatisticsWheels',
  'm10_5_1': 'LabM10ComplexApplications',
  'm10_5_2': 'LabM10QuadraticApplications',
  'm10_5_3': 'LabM10MatrixApplications',
  'm10_5_4': 'LabM10InequalityApplications',
  'm10_5_5': 'LabM10FractionApplications',
  'm10_5_6': 'LabM10FunctionApplications',
  'm10_5_7': 'LabM10VectorApplications',
  'm10_5_8': 'LabM10TrigApplications',
  'm10_5_9': 'LabM10CircleApplications',
  'm10_5_10': 'LabM10StatsApplications',

  // Class 10 Biology
  'b10_1_1': 'LabB10DigestiveSystem',
  'b10_1_2': 'LabB10BloodSmear',
  'b10_1_3': 'LabB10RespiratorySystem',
  'b10_1_4': 'LabB10KidneyDissection',
  'b10_1_5': 'LabB10NervousSystem',
  'b10_1_6': 'LabB10Genetics',
  'b10_1_7': 'LabB10Biostatistics',

  // Class 9 Biology
  'b9_1_1': 'LabB9Biodiversity',
  'b9_1_2': 'LabB9Microscopy',
  'b9_1_3': 'LabB9Biochemistry',
  'b9_1_4': 'LabB9Enzymes',
  'b9_1_5': 'LabB9PlantPhysiology',
  'b9_1_6': 'LabB9PlantReproduction',

  // Class 9 Chemistry
  'c9_1_1': 'LabC9StatesOfMatter',
  'c9_1_2': 'LabC9AtomicStructure',
  'c9_1_3': 'LabC9Electrochemistry',
  'c9_1_4': 'LabC9EnvironmentalChem',
  'c9_1_5': 'LabC9OrganicChem',
  'c9_1_6': 'LabC9SeparationTech',
  'c9_1_7': 'LabC9QualitativeAnalysis',

  // Class 9 Physics
  'p9_1_1': 'LabP9MeasurementTools',
  'p9_1_2': 'LabP9VolumeDensity',
  'p9_1_3': 'LabP9Kinematics',
  'p9_1_4': 'LabP9Inertia',
  'p9_1_5': 'LabP9Friction',
  'p9_1_6': 'LabP9Pressure',
  'p9_1_7': 'LabP9Springs',
  'p9_1_8': 'LabP9MagnetismFields',
  'p9_1_9': 'LabP9MagnetismInduction',
  'p9_1_10': 'LabP9EverydayPhysics',

  // Class 9 Computer Science
  'cs9_1_1': 'LabCS9ComputerSystems',
  'cs9_1_2': 'LabCS9Algorithms',
  'cs9_1_3': 'LabCS9WebBasics',
  'cs9_1_4': 'LabCS9JavaScript',
  'cs9_1_5': 'LabCS9WebProjects',
  'cs9_1_6': 'LabCS9DataAnalysis',
  'cs9_1_7': 'LabCS9AIApplications',
  'cs9_1_8': 'LabCS9CyberSafety',
  'cs9_1_9': 'LabCS9Entrepreneurship',

  // Class 9 Mathematics
  'm9_1_1': 'LabM9RealNumbers',
  'm9_1_2': 'LabM9Logarithms',
  'm9_1_3': 'LabM9SetsRelations',
  'm9_1_4': 'LabM9AlgebraicManipulation',
  'm9_1_5': 'LabM9Trigonometry',
  'm9_1_6': 'LabM9CoordinateGeometry',
  'm9_1_7': 'LabM9LinearGraphs',
  'm9_1_8': 'LabM9GeometryPolygons',
  'm9_1_9': 'LabM9BasicStatistics',

  // Class 11 Chemistry
  'c11_1_1': 'LabC11AtomicStructure',
  'c11_1_2': 'LabC11MolecularBonding',
  'c11_1_3': 'LabC11Stoichiometry',
  'c11_1_4': 'LabC11PhasesOfMatter',
  'c11_1_5': 'LabC11EnergeticsKinetics',
  'c11_1_6': 'LabC11IndustrialEquilibrium',
  'c11_1_7': 'LabC11AcidsBases',
  'c11_1_8': 'LabC11EnvironmentalChem',
  'c11_1_9': 'LabC11OrganicAnalysis',
  'c11_1_10': 'LabC11OrganicSynthesis',

  // Class 11 Physics
  'p11_1_1': 'LabP11PhysicalQuantities',
  'p11_1_2': 'LabP11Vectors',
  'p11_1_3': 'LabP11TranslatoryMotion',
  'p11_1_4': 'LabP11RotationalMotion',
  'p11_1_5': 'LabP11WorkEnergy',
  'p11_1_6': 'LabP11FluidMechanics',
  'p11_1_7': 'LabP11Solids',
  'p11_1_8': 'LabP11Thermodynamics',
  'p11_1_9': 'LabP11Waves',
  'p11_1_10': 'LabP11Electrostatics',
  'p11_1_11': 'LabP11Electricity',
  'p11_1_12': 'LabP11Electromagnetism',
  'p11_1_13': 'LabP11ModernPhysics',

  // Class 11 Computer Science
  'cs11_1_1': 'LabCS11SystemsNetworks',
  'cs11_1_2': 'LabCS11Algorithms',
  'cs11_1_3': 'LabCS11Python',
  'cs11_1_4': 'LabCS11DataScience',
  'cs11_1_5': 'LabCS11Applications',
  'cs11_1_6': 'LabCS11Impacts',
  'cs11_1_7': 'LabCS11Research',
  'cs11_1_8': 'LabCS11ProductDev',

  // Class 11 Biology
  'b11_1_1': 'LabB11Cytology',
  'b11_1_2': 'LabB11Biomolecules',
  'b11_1_3': 'LabB11Enzymes',
  'b11_1_4': 'LabB11Bioenergetics',
  'b11_1_5': 'LabB11Microbiology',
  'b11_1_6': 'LabB11Fungi',
  'b11_1_7': 'LabB11PlantPhysiology',
  'b11_1_8': 'LabB11Inheritance',
  'b11_1_9': 'LabB11Genetics',

  // Class 12 Biology
  'b12_1_1': 'LabB12Digestive',
  'b12_1_2': 'LabB12Cardiorespiratory',
  'b12_1_3': 'LabB12Urinary',
  'b12_1_4': 'LabB12NeuroEndocrine',
  'b12_1_5': 'LabB12Skeletal',
  'b12_1_6': 'LabB12Immunity',
  'b12_1_7': 'LabB12Biotechnology',
  'b12_1_8': 'LabB12StructuralStats',
  'b12_1_9': 'LabB12PharmacologyEcology',

  // Class 12 Physics
  'p12_1_1': 'LabP12Gravitation',
  'p12_1_2': 'LabP12ThermoMechanics',
  'p12_1_3': 'LabP12SHM',
  'p12_1_4': 'LabP12Diffraction',
  'p12_1_5': 'LabP12ElectricPotential',
  'p12_1_6': 'LabP12AlternatingCurrent',
  'p12_1_7': 'LabP12QuantumNuclear',
  'p12_1_8': 'LabP12CosmologyClimate',
  'p12_1_9': 'LabP12MedicalImaging',

  // Class 12 Chemistry
  'c12_1_1': 'LabC12Electrochemistry',
  'c12_1_2': 'LabC12EquilibriumAcidBase',
  'c12_1_3': 'LabC12TransitionMetals',
  'c12_1_4': 'LabC12OrganicSynthesis',
  'c12_1_5': 'LabC12Biochemistry',
  'c12_1_6': 'LabC12SpectroscopyChromatography',
  'c12_1_7': 'LabC12Medicine',
  'c12_1_8': 'LabC12Agriculture',
  'c12_1_9': 'LabC12IndustryMaterials',

  // Class 12 Computer Science
  'cs12_1_1': 'LabCS12HCI',
  'cs12_1_2': 'LabCS12DataStructures',
  'cs12_1_3': 'LabCS12Programming',
  'cs12_1_4': 'LabCS12MachineLearning',
  'cs12_1_5': 'LabCS12DeepLearning',
  'cs12_1_6': 'LabCS12IoTCloud',
  'cs12_1_7': 'LabCS12Cybersecurity',
  'cs12_1_8': 'LabCS12DigitalLiteracy',
  'cs12_1_9': 'LabCS12Entrepreneurship',

  // Class 11 Mathematics
  'm11_1_1': 'LabM11ComplexNumbers',
  'm11_1_2': 'LabM11Matrices',
  'm11_1_3': 'LabM11Vectors',
  'm11_1_4': 'LabM11SequencesSeries',
  'm11_1_5': 'LabM11Polynomials',
  'm11_1_6': 'LabM11Trigonometry',
  'm11_1_7': 'LabM11Permutations',
  'm11_1_8': 'LabM11BinomialInduction',

  // Class 12 Mathematics
  'm12_1_1': 'LabM12Derivatives',
  'm12_1_2': 'LabM12Integration',
  'm12_1_3': 'LabM12DifferentialEq',
  'm12_1_4': 'LabM12Conics',
  'm12_1_5': 'LabM12AnalyticalGeometry',
  'm12_1_6': 'LabM12Kinematics',
  'm12_1_7': 'LabM12Functions',
  'm12_1_8': 'LabM12InverseTrig',

  // Class 6 Science
  'c6s_1_1': 'LabS6Microscope',
  'c6s_1_3': 'LabS6Unit1Projects',
  'c6s_2_1': 'LabS6VegetativePropagation',
  'c6s_3_1': 'LabS6FatDetection',
  'c6s_3_2': 'LabS6BalancedDiet',
  'c6s_4_1': 'LabS6DigestionMechanics',
  'c6s_4_2': 'LabS6AlimentaryCanal',
  'c6s_4_4': 'LabS6LungModel',
  'c6s_5_1': 'LabS6ParticleSimulation',
  'c6s_6_1': 'LabS6MolecularBuilder',
  'c6s_6_2': 'LabS6ElementsCompounds',
  'c6s_7_1': 'LabS6Separation',
  'c6s_7_2': 'LabS6SolutionInvestigation',
  'c6s_8_1': 'LabS6EnergyTransformation',
  'c6s_8_2': 'LabS6EnergyProjects',
  'c6s_9_1': 'LabS6CircuitBuilder',
  'c6s_9_2': 'LabS6ConductorsInsulators',
  'c6s_10_1': 'LabS6Magnetism',
  'c6s_11_1': 'LabS6PlantGrowth',
  'c6s_12_1': 'LabS6SolarSystemBuilder',
  'c6s_12_2': 'LabS6EverydayTech',
  // (Class 8 Science mappings above are now correct, duplicates removed)
  'c10_10_3': 'LabC10AlcoholCombustion',
  'c10_12_2': 'LabC10CondensationPolymerisation',
  'c10_12_3': 'LabC10PETAcidHydrolysis',
  'cs10_3_2': 'LabCS10JSAlgorithms',
  'cs10_3_3': 'LabCS10DynamicList',
  'cs10_4_2': 'LabCS10ChurnPrediction',
  'cs10_8_2': 'LabCS10Financials',
  'cs10_8_3': 'LabCS10BusinessPitch',
  'm10_7_1': 'LabM10Vectors',
  'm10_9_1': 'LabM10ChordBisectors',
  'm10_9_2': 'LabM10EqualChords',
  'm10_10_1': 'LabM10TangentProperties',
  'm10_10_2': 'LabM10CircleAngles',
  'm10_11_1': 'LabM10CircleBasics',
  'm10_11_2': 'LabM10TangentConstruction',
  'm10_11_3': 'LabM10CommonTangents',
  'm10_12_1': 'LabM10StatisticsWheels',
  'm10_app_1': 'LabM10ComplexApplications',
  'm10_app_2': 'LabM10QuadraticApplications',
  'm10_app_3': 'LabM10MatrixApplications',
  'm10_app_4': 'LabM10InequalityApplications',
  'm10_app_5': 'LabM10FractionApplications',
  'm10_app_6': 'LabM10FunctionApplications',
  'm10_app_7': 'LabM10VectorApplications',
  'm10_app_8': 'LabM10TrigApplications',
  'm10_app_9': 'LabM10CircleApplications',
  'm10_app_12': 'LabM10StatsApplications',
  'b10_1': 'LabB10DigestiveSystem',
  'b10_2': 'LabB10BloodSmear',
  'b10_3': 'LabB10RespiratorySystem',
  'b10_4': 'LabB10KidneyDissection',
  'b10_5': 'LabB10NervousSystem',
  'b10_7': 'LabB10Genetics',
  'b10_11': 'LabB10Biostatistics',
  'b9_1': 'LabB9Biodiversity',
  'b9_3': 'LabB9Microscopy',
  'b9_6': 'LabB9Biochemistry',
  'b9_7': 'LabB9Enzymes',
  'b9_8': 'LabB9PlantPhysiology',
  'b9_9': 'LabB9PlantReproduction',
  'c9_1': 'LabC9StatesOfMatter',
  'c9_2': 'LabC9AtomicStructure',
  'c9_3': 'LabC9Electrochemistry',
  'c9_4': 'LabC9EnvironmentalChem',
  'c9_5': 'LabC9OrganicChem',
  'c9_6': 'LabC9SeparationTech',
  'c9_7': 'LabC9QualitativeAnalysis',
  'p9_1': 'LabP9MeasurementTools',
  'p9_2': 'LabP9VolumeDensity',
  'p9_3': 'LabP9Kinematics',
  'p9_4': 'LabP9Inertia',
  'p9_5': 'LabP9Friction',
  'p9_6': 'LabP9Pressure',
  'p9_7': 'LabP9Springs',
  'p9_8': 'LabP9MagnetismFields',
  'p9_9': 'LabP9MagnetismInduction',
  'p9_10': 'LabP9EverydayPhysics',
  'cs9_1': 'LabCS9ComputerSystems',
  'cs9_2': 'LabCS9Algorithms',
  'cs9_3': 'LabCS9WebBasics',
  'cs9_4': 'LabCS9JavaScript',
  'cs9_5': 'LabCS9WebProjects',
  'cs9_6': 'LabCS9DataAnalysis',
  'cs9_7': 'LabCS9AIApplications',
  'cs9_8': 'LabCS9CyberSafety',
  'cs9_9': 'LabCS9Entrepreneurship',
  'm9_1': 'LabM9RealNumbers',
  'm9_2': 'LabM9Logarithms',
  'm9_3': 'LabM9SetsRelations',
  'm9_4': 'LabM9AlgebraicManipulation',
  'm9_5': 'LabM9Trigonometry',
  'm9_6': 'LabM9CoordinateGeometry',
  'm9_7': 'LabM9LinearGraphs',
  'm9_8': 'LabM9GeometryPolygons',
  'm9_9': 'LabM9BasicStatistics',
  'c11_1': 'LabC11AtomicStructure',
  'c11_2': 'LabC11MolecularBonding',
  'c11_3': 'LabC11Stoichiometry',
  'c11_4': 'LabC11PhasesOfMatter',
  'c11_5': 'LabC11EnergeticsKinetics',
  'c11_6': 'LabC11IndustrialEquilibrium',
  'c11_7': 'LabC11AcidsBases',
  'c11_8': 'LabC11EnvironmentalChem',
  'c11_9': 'LabC11OrganicAnalysis',
  'c11_10': 'LabC11OrganicSynthesis',
  'p11_1': 'LabP11PhysicalQuantities',
  'p11_2': 'LabP11Vectors',
  'p11_3': 'LabP11TranslatoryMotion',
  'p11_4': 'LabP11RotationalMotion',
  'p11_5': 'LabP11WorkEnergy',
  'p11_6': 'LabP11FluidMechanics',
  'p11_7': 'LabP11Solids',
  'p11_8': 'LabP11Thermodynamics',
  'p11_9': 'LabP11Waves',
  'p11_10': 'LabP11Electrostatics',
  'p11_11': 'LabP11Electricity',
  'p11_12': 'LabP11Electromagnetism',
  'p11_13': 'LabP11ModernPhysics',
  'cs11_1': 'LabCS11SystemsNetworks',
  'cs11_2': 'LabCS11Algorithms',
  'cs11_3': 'LabCS11Python',
  'cs11_4': 'LabCS11DataScience',
  'cs11_5': 'LabCS11Applications',
  'cs11_6': 'LabCS11Impacts',
  'cs11_7': 'LabCS11Research',
  'cs11_8': 'LabCS11ProductDev',
  'b11_1': 'LabB11Cytology',
  'b11_2': 'LabB11Biomolecules',
  'b11_3': 'LabB11Enzymes',
  'b11_4': 'LabB11Bioenergetics',
  'b11_5': 'LabB11Microbiology',
  'b11_6': 'LabB11Fungi',
  'b11_7': 'LabB11PlantPhysiology',
  'b11_8': 'LabB11Inheritance',
  'b11_9': 'LabB11Genetics',
  'b12_1': 'LabB12Digestive',
  'b12_2': 'LabB12Cardiorespiratory',
  'b12_3': 'LabB12Urinary',
  'b12_4': 'LabB12NeuroEndocrine',
  'b12_5': 'LabB12Skeletal',
  'b12_6': 'LabB12Immunity',
  'b12_7': 'LabB12Biotechnology',
  'b12_8': 'LabB12StructuralStats',
  'b12_9': 'LabB12PharmacologyEcology',
  'm11_1': 'LabM11ComplexNumbers',
  'm11_2': 'LabM11Matrices',
  'm11_3': 'LabM11Vectors',
  'm11_4': 'LabM11SequencesSeries',
  'm11_5': 'LabM11Polynomials',
  'm11_6': 'LabM11Permutations',
  'm11_7': 'LabM11BinomialInduction',
  'm11_8': 'LabM11Trigonometry',
  'm12_1': 'LabM12Derivatives',
  'm12_2': 'LabM12Integration',
  'm12_3': 'LabM12DifferentialEq',
  'm12_4': 'LabM12Conics',
  'm12_5': 'LabM12AnalyticalGeometry',
  'm12_6': 'LabM12Kinematics',
  'm12_7': 'LabM12Functions',
  'm12_8': 'LabM12InverseTrig',
  'p12_1': 'LabP12Gravitation',
  'p12_2': 'LabP12ThermoMechanics',
  'p12_3': 'LabP12SHM',
  'p12_4': 'LabP12Diffraction',
  'p12_5': 'LabP12ElectricPotential',
  'p12_6': 'LabP12AlternatingCurrent',
  'p12_7': 'LabP12QuantumNuclear',
  'p12_8': 'LabP12CosmologyClimate',
  'p12_9': 'LabP12MedicalImaging',
  'c12_1': 'LabC12Electrochemistry',
  'c12_2': 'LabC12EquilibriumAcidBase',
  'c12_3': 'LabC12TransitionMetals',
  'c12_4': 'LabC12OrganicSynthesis',
  'c12_5': 'LabC12Biochemistry',
  'c12_6': 'LabC12SpectroscopyChromatography',
  'c12_7': 'LabC12Medicine',
  'c12_8': 'LabC12Agriculture',
  'c12_9': 'LabC12IndustryMaterials',
  'cs12_1': 'LabCS12HCI',
  'cs12_2': 'LabCS12DataStructures',
  'cs12_3': 'LabCS12Programming',
  'cs12_4': 'LabCS12MachineLearning',
  'cs12_5': 'LabCS12DeepLearning',
  'cs12_6': 'LabCS12IoTCloud',
  'cs12_7': 'LabCS12Cybersecurity',
  'cs12_8': 'LabCS12DigitalLiteracy',
  'cs12_9': 'LabCS12Entrepreneurship',

  // Class 8 Math
  'm8_1': 'LabM8RealEstimation',
  'm8_2': 'LabM8RootsFinance',
  'm8_3': 'LabM8SetsAlgebra',
  'm8_4': 'LabM8EquationsInequalities',
  'm8_5': 'LabM8Transformations',
  'm8_6': 'LabM8GeometryTriangles',
  'm8_7': 'LabM8Mensuration',
  'm8_8': 'LabM8DataProbability',

  // Class 6 English
  'e6_1': 'LabE6NounsPronouns',
  'e6_2': 'LabE6SentencesAffixes',
  'e6_3': 'LabE6VerbsAdverbs',
  'e6_4': 'LabE6PrepositionsStructure',
  'e6_5': 'LabE6ClausesConjunctions',
  'e6_6': 'LabE6TensesPunctuation',
  'e6_7': 'LabE6FiguresOfSpeech',
  'e6_8': 'LabE6WritingMechanics',

  // Class 7 English
  'e7_1': 'LabE7ArticlesAdjectives',
  'e7_2': 'LabE7FiguresOfSpeech',
  'e7_3': 'LabE7PrepositionsModals',
  'e7_4': 'LabE7VerbsCollocations',
  'e7_5': 'LabE7Tenses',
  'e7_6': 'LabE7Conjunctions',
  'e7_7': 'LabE7PronounsClauses',
  'e7_8': 'LabE7VocabPunctuation',


  // Class 8 English
  'e8_1': 'LabE8NounsPhonetics',
  'e8_2': 'LabE8PronounsMorphology',
  'e8_3': 'LabE8AdjectivesPoetry',
  'e8_4': 'LabE8VerbsModals',
  'e8_5': 'LabE8AdverbsPrepositions',
  'e8_6': 'LabE8ConjunctionsClauses',
  'e8_7': 'LabE8TensesVoice',
  'e8_8': 'LabE8NarrationConditionals',

  // Class 9 English
  'c9e_1': 'LabE9PartsOfSpeech',
  'c9e_2': 'LabE9Verbals',
  'c9e_3': 'LabE9TensesAgreement',
  'c9e_4': 'LabE9Phrases',
  'c9e_5': 'LabE9PrepositionsConjunctions',
  'c9e_6': 'LabE9SentenceStructure',
  'c9e_7': 'LabE9Narration',
  'c9e_8': 'LabE9PunctuationVocabulary',
  
  // Class 10 English
  'c10e_1': 'LabE10NounsPronouns',
  'c10e_2': 'LabE10VerbsAdjectives',
  'c10e_3': 'LabE10AdverbsPrepositions',
  'c10e_4': 'LabE10ConjunctionsTenses',
  'c10e_5': 'LabE10ModalsConditionals',
  'c10e_6': 'LabE10PhrasesClauses',
  'c10e_7': 'LabE10SentenceNarration',
  'c10e_8': 'LabE10VocabularyStylistics',
  
  // Class 11 English
  'c11e_1': 'LabE11NounsPronouns',
  'c11e_2': 'LabE11AdjectivesAdverbs',
  'c11e_3': 'LabE11PrepositionsConjunctions',
  'c11e_4': 'LabE11VerbsModals',
  'c11e_5': 'LabE11TensesVerbals',
  'c11e_6': 'LabE11PhrasesClauses',
  'c11e_7': 'LabE11SentenceStructure',
  'c11e_8': 'LabE11VocabularyStylistics',

  // Class 12 English
  'e12-1': 'LabE12NounsPronouns',
  'e12-2': 'LabE12AdjectivesAdverbs',
  'e12-3': 'LabE12PrepositionsConjunctions',
  'e12-4': 'LabE12VerbsModals',
  'e12-5': 'LabE12TensesVerbals',
  'e12-6': 'LabE12PhrasesClauses',
  'e12-7': 'LabE12SentenceStructure',
  'e12-8': 'LabE12VocabularyStylistics',
};

// Get component by module ID
export const getLabComponent = (moduleId: string): React.LazyExoticComponent<React.ComponentType<any>> | null => {
  const componentName = moduleIdToComponent[moduleId];
  if (!componentName) return null;
  return labComponents[componentName] || null;
}
