import { useState } from 'react';
import { ArrowLeft, CheckCircle2, XCircle, TrendingDown, Biohazard } from 'lucide-react';

export default function LabM10FunctionApplications({ onExit }: { onExit: () => void }) {
  const [mode, setMode] = useState<'virus' | 'depreciation'>('virus');

  // Virus state
  const [r0, setR0] = useState(1.5);
  const [days, setDays] = useState(0); 

  // Depreciation state
  const [initialValue] = useState(10000);
  const [rate, setRate] = useState(15); 
  const [year, setYear] = useState(5);

  // Assessment state
  const [ans, setAns] = useState('');
  const [status, setStatus] = useState<'none' | 'correct' | 'incorrect'>('none');

  const resetAns = () => {
    setAns('');
    setStatus('none');
  };

  const handleModeChange = (m: 'virus' | 'depreciation') => {
    setMode(m);
    resetAns();
  };

  // Virus logic
  const gridCols = 20;
  const gridCells = 400; // 20x20
  const infectedCount = Math.min(gridCells, Math.floor(1 * Math.pow(r0, days)));

  // Depreciation logic
  const linearValue = Math.max(0, initialValue - (initialValue * (rate/100)) * year);
  const expValue = initialValue * Math.pow(1 - rate/100, year);

  const checkAns = () => {
    let correct = 0;
    if (mode === 'virus') {
      correct = Math.ceil(Math.log(200) / Math.log(r0));
    } else {
      const lin = Math.max(0, initialValue - (initialValue * (rate/100)) * year);
      const exp = initialValue * Math.pow(1 - rate/100, year);
      correct = Math.round(Math.abs(lin - exp));
    }
    
    if (Math.abs(parseFloat(ans) - correct) <= 1.0) {
      setStatus('correct');
    } else {
      setStatus('incorrect');
    }
  };

  // SVG drawing for depreciation
  const width = 400;
  const height = 240;
  const padding = 30;
  const maxYear = 10;

  const getLinePath = (isLinear: boolean) => {
    let path = `M ${padding} ${height - padding}`;
    for (let y = 0; y <= maxYear; y++) {
      const val = isLinear 
        ? Math.max(0, initialValue - (initialValue * (rate/100)) * y)
        : initialValue * Math.pow(1 - rate/100, y);
      
      const px = padding + (y / maxYear) * (width - 2 * padding);
      const py = height - padding - (val / initialValue) * (height - 2 * padding);
      if (y === 0) path = `M ${px} ${py}`;
      else path += ` L ${px} ${py}`;
    }
    return path;
  };

  return (
    <div className="flex flex-col h-screen overflow-y-auto bg-slate-50 font-sans select-none">
      <div className="bg-slate-800 text-white p-4 flex items-center shadow-md shrink-0">
        <button onClick={onExit} className="flex items-center text-slate-300 hover:text-white transition-colors">
          <ArrowLeft className="mr-2" size={20} />
          Back to Dashboard
        </button>
        <h1 className="text-xl font-bold ml-6">Mathematical Function Applications Lab</h1>
      </div>

      <div className="flex-1 grid grid-cols-1 lg:grid-cols-3 gap-6 p-6">
        {/* Theory Column */}
        <div className="bg-white rounded-xl shadow-sm p-6 border border-slate-200 flex flex-col">
          <h2 className="text-lg font-bold text-slate-800 mb-4 border-b pb-2">Theory & Formulas</h2>
          <div className="flex-1 overflow-y-auto pr-2 space-y-4 text-slate-700">
            {mode === 'virus' ? (
              <>
                <p><strong>Exponential Growth</strong> functions describe scenarios where a quantity increases by a constant factor over equal time intervals.</p>
                <div className="bg-purple-50 p-4 rounded-lg text-center font-mono font-bold text-purple-800">
                  N(t) = N₀ × (R₀)ᵗ
                </div>
                <p>In epidemiology, N₀ is the initial number of infected individuals, and R₀ (the basic reproduction number) represents how many secondary infections are generated by one infected person.</p>
                <ul className="list-disc pl-5 space-y-1 text-sm">
                  <li>If R₀ &gt; 1, the spread is exponential.</li>
                  <li>If R₀ &lt; 1, the spread will die out.</li>
                </ul>
              </>
            ) : (
              <>
                <p><strong>Depreciation</strong> models how the value of an asset decreases over time. There are two common mathematical models.</p>
                <p className="font-semibold mt-4">1. Linear (Straight-Line)</p>
                <div className="bg-red-50 p-3 rounded-lg text-center font-mono font-bold text-red-800 text-sm">
                  V(t) = V₀ - (V₀ × r) × t
                </div>
                <p className="text-sm">Value drops by a fixed <em>amount</em> every year.</p>
                
                <p className="font-semibold mt-4">2. Exponential (Reducing Balance)</p>
                <div className="bg-blue-50 p-3 rounded-lg text-center font-mono font-bold text-blue-800 text-sm">
                  V(t) = V₀ × (1 - r)ᵗ
                </div>
                <p className="text-sm">Value drops by a fixed <em>percentage</em> of its current value every year.</p>
              </>
            )}
          </div>
        </div>

        {/* Interactive Column */}
        <div className="bg-white rounded-xl shadow-sm p-6 border border-slate-200 flex flex-col">
          <div className="flex space-x-2 mb-6">
            <button 
              onClick={() => handleModeChange('virus')}
              className={`flex-1 flex items-center justify-center py-2 rounded-lg font-medium transition-colors ${mode === 'virus' ? 'bg-purple-600 text-white' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}
            >
              <Biohazard size={18} className="mr-2" /> Viral Spread
            </button>
            <button 
              onClick={() => handleModeChange('depreciation')}
              className={`flex-1 flex items-center justify-center py-2 rounded-lg font-medium transition-colors ${mode === 'depreciation' ? 'bg-emerald-600 text-white' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}
            >
              <TrendingDown size={18} className="mr-2" /> Depreciation
            </button>
          </div>

          {/* Visualizer */}
          <div className="relative h-64 bg-slate-100 rounded-xl mb-6 overflow-hidden border border-slate-200 flex items-center justify-center p-4">
            {mode === 'virus' ? (
              <div className="w-full h-full flex flex-col items-center justify-center">
                <div className="grid gap-[2px] bg-slate-300 p-2 rounded-lg" style={{ gridTemplateColumns: `repeat(${gridCols}, minmax(0, 1fr))` }}>
                  {Array.from({ length: gridCells }).map((_, i) => (
                    <div key={i} className={`w-3 h-3 sm:w-4 sm:h-4 rounded-sm ${i < infectedCount ? 'bg-purple-600' : 'bg-white'}`} />
                  ))}
                </div>
                <div className="mt-4 font-bold text-slate-700 bg-white px-4 py-1 rounded-full shadow-sm">
                  Day {days}: <span className="text-purple-600">{infectedCount}</span> Infected
                </div>
              </div>
            ) : (
              <div className="w-full h-full flex flex-col">
                <div className="flex justify-between px-8 text-xs font-bold mb-2">
                  <span className="text-red-500">Linear: ${Math.round(linearValue)}</span>
                  <span className="text-blue-500">Exponential: ${Math.round(expValue)}</span>
                </div>
                <svg viewBox={`0 0 ${width} ${height}`} className="w-full flex-1">
                  {/* Grid / Axes */}
                  <line x1={padding} y1={height - padding} x2={width - padding} y2={height - padding} stroke="#cbd5e1" strokeWidth="2" />
                  <line x1={padding} y1={padding} x2={padding} y2={height - padding} stroke="#cbd5e1" strokeWidth="2" />
                  
                  {/* Labels */}
                  <text x={padding - 5} y={padding + 5} fontSize="10" textAnchor="end" fill="#64748b">$10k</text>
                  <text x={padding - 5} y={height - padding} fontSize="10" textAnchor="end" fill="#64748b">$0</text>
                  <text x={width - padding} y={height - padding + 15} fontSize="10" textAnchor="middle" fill="#64748b">Yr 10</text>
                  
                  {/* Paths */}
                  <path d={getLinePath(true)} fill="none" stroke="#ef4444" strokeWidth="3" strokeDasharray="5,5" />
                  <path d={getLinePath(false)} fill="none" stroke="#3b82f6" strokeWidth="3" />
                  
                  {/* Current year marker */}
                  <line 
                    x1={padding + (year / maxYear) * (width - 2 * padding)} 
                    y1={padding} 
                    x2={padding + (year / maxYear) * (width - 2 * padding)} 
                    y2={height - padding} 
                    stroke="#10b981" strokeWidth="2" strokeDasharray="4,4" 
                  />
                  <circle cx={padding + (year / maxYear) * (width - 2 * padding)} cy={height - padding - (expValue / initialValue) * (height - 2 * padding)} r="5" fill="#3b82f6" />
                  <circle cx={padding + (year / maxYear) * (width - 2 * padding)} cy={height - padding - (linearValue / initialValue) * (height - 2 * padding)} r="5" fill="#ef4444" />
                </svg>
              </div>
            )}
          </div>

          {/* Sliders */}
          <div className="space-y-5">
            {mode === 'virus' ? (
              <>
                <div>
                  <div className="flex justify-between text-sm font-medium text-purple-700 mb-1">
                    <span>Reproduction Rate (R₀)</span>
                    <span>{r0.toFixed(1)}</span>
                  </div>
                  <input type="range" min="1.1" max="3.0" step="0.1" value={r0} onChange={e => {setR0(Number(e.target.value)); resetAns()}} className="w-full accent-purple-600" />
                </div>
                <div>
                  <div className="flex justify-between text-sm font-medium text-slate-700 mb-1">
                    <span>Days Elapsed</span>
                    <span>Day {days}</span>
                  </div>
                  <input type="range" min="0" max="15" step="1" value={days} onChange={e => {setDays(Number(e.target.value)); resetAns()}} className="w-full" />
                </div>
              </>
            ) : (
              <>
                <div>
                  <div className="flex justify-between text-sm font-medium text-slate-700 mb-1">
                    <span>Depreciation Rate (%)</span>
                    <span>{rate}% / year</span>
                  </div>
                  <input type="range" min="5" max="30" step="1" value={rate} onChange={e => {setRate(Number(e.target.value)); resetAns()}} className="w-full accent-emerald-600" />
                </div>
                <div>
                  <div className="flex justify-between text-sm font-medium text-emerald-700 mb-1">
                    <span>Years Elapsed</span>
                    <span>Year {year}</span>
                  </div>
                  <input type="range" min="0" max="10" step="1" value={year} onChange={e => {setYear(Number(e.target.value)); resetAns()}} className="w-full accent-emerald-600" />
                </div>
              </>
            )}
          </div>
        </div>

        {/* Assessment Column */}
        <div className="bg-white rounded-xl shadow-sm p-6 border border-slate-200 flex flex-col">
          <h2 className="text-lg font-bold text-slate-800 mb-4 border-b pb-2">Data Analysis</h2>
          <div className="flex-1 space-y-6">
            <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
              <p className="text-slate-700 font-medium mb-3">
                {mode === 'virus' 
                  ? `If R₀ is ${r0.toFixed(1)}, on what exact day will the number of infected individuals first reach or exceed 200?` 
                  : `At year ${year}, what is the absolute difference between the linear and exponential depreciated values?`}
              </p>
              <p className="text-xs text-slate-500 mb-4">(Round to nearest whole number)</p>
              
              <div className="flex items-center space-x-3">
                <input 
                  type="number" 
                  value={ans}
                  onChange={e => setAns(e.target.value)}
                  placeholder="e.g. 5"
                  className="flex-1 px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500"
                />
                <button 
                  onClick={checkAns}
                  className="px-4 py-2 bg-slate-800 text-white rounded-lg hover:bg-slate-700 transition-colors"
                >
                  Check
                </button>
              </div>

              {status === 'correct' && (
                <div className="mt-4 p-3 bg-green-50 text-green-700 rounded-lg flex items-center">
                  <CheckCircle2 size={20} className="mr-2 shrink-0" />
                  <span className="font-medium">Correct! Great calculation.</span>
                </div>
              )}
              {status === 'incorrect' && (
                <div className="mt-4 p-3 bg-red-50 text-red-700 rounded-lg flex items-center">
                  <XCircle size={20} className="mr-2 shrink-0" />
                  <span className="font-medium">Not quite right. Try again using the formulas.</span>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
