import { useState, useEffect, useRef } from 'react';
import { ArrowLeft, Activity, Bone, Waves } from 'lucide-react';

export default function LabP12MedicalImaging({ onExit }: { onExit?: () => void }) {
  const [tissueDepth, setTissueDepth] = useState(5); 
  const [pulseActive, setPulseActive] = useState(false);
  const [echoTime, setEchoTime] = useState(0); 
  
  const [boneThickness, setBoneThickness] = useState(2); 
  const [muscleThickness, setMuscleThickness] = useState(8); 
  
  const muBone = 0.5;
  const muMuscle = 0.1;
  const initialIntensity = 100;
  
  const intensity = initialIntensity * Math.exp(-muBone * boneThickness - muMuscle * muscleThickness);
  
  const [usAns, setUsAns] = useState('');
  const [xrAns, setXrAns] = useState('');
  const [usFeedback, setUsFeedback] = useState('');
  const [xrFeedback, setXrFeedback] = useState('');

  const pulsePosRef = useRef(0);
  const pulseDirRef = useRef(1); 
  const [renderPulsePos, setRenderPulsePos] = useState(0);
  
  useEffect(() => {
    if (!pulseActive) return;
    
    const interval = setInterval(() => {
      const speed = 2;
      pulsePosRef.current += speed * pulseDirRef.current;
      
      const targetDepthPixels = tissueDepth * 20; 
      
      if (pulseDirRef.current === 1 && pulsePosRef.current >= targetDepthPixels) {
        pulseDirRef.current = -1; 
      } else if (pulseDirRef.current === -1 && pulsePosRef.current <= 0) {
        setPulseActive(false);
        pulsePosRef.current = 0;
        pulseDirRef.current = 1;
        
        setEchoTime(Math.round((tissueDepth * 2) / 0.154));
        clearInterval(interval);
      }
      setRenderPulsePos(pulsePosRef.current);
      
    }, 16);
    
    return () => clearInterval(interval);
  }, [pulseActive, tissueDepth]);

  const triggerPulse = () => {
    if (pulseActive) return;
    setPulseActive(true);
    setEchoTime(0);
    pulsePosRef.current = 0;
    pulseDirRef.current = 1;
  };

  const checkUS = () => {
    const v = parseFloat(usAns);
    if (v >= 7.6 && v <= 7.8) setUsFeedback('Correct! ~7.7 cm');
    else setUsFeedback('Incorrect. Use d = v*t / 2');
  };

  const checkXR = () => {
    const v = parseFloat(xrAns);
    if (v >= 21 && v <= 23) setXrFeedback('Correct! ~22.3%');
    else setXrFeedback('Incorrect. Use I = I₀ e^(-μx)');
  };

  return (
    <div className="flex flex-col h-screen overflow-y-auto bg-slate-50 font-sans select-none">
      <div className="bg-slate-900 text-white p-4 flex items-center justify-between shadow-md">
        <div className="flex items-center gap-3">
          <button onClick={onExit} className="p-2 hover:bg-slate-800 rounded-full transition-colors">
            <ArrowLeft size={20} />
          </button>
          <h1 className="text-xl font-bold">Lab 12.3: Medical Imaging Physics</h1>
        </div>
        <div className="flex items-center gap-4 text-sm">
          <Activity size={16} className="text-pink-400" /> Diagnostic Mode
        </div>
      </div>

      <div className="flex-1 grid grid-cols-1 lg:grid-cols-3 gap-4 p-4 min-h-0">
        <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-5 overflow-y-auto">
          <h2 className="text-lg font-bold text-slate-800 mb-3 border-b pb-2">Theory</h2>
          
          <div className="space-y-4 text-slate-700 text-sm leading-relaxed">
            <section>
              <h3 className="font-semibold text-slate-900 flex items-center gap-2">
                <Waves size={16} className="text-blue-500"/> Piezoelectric Ultrasound
              </h3>
              <p className="mt-1">
                Ultrasound uses high-frequency sound waves (1-10 MHz) generated by piezoelectric crystals. The waves travel through tissue (v ≈ 1540 m/s) and partially reflect at boundaries with different acoustic impedances.
              </p>
              <p className="mt-2 font-mono text-xs bg-slate-100 p-2 rounded">Depth = (v × t) / 2</p>
            </section>

            <section>
              <h3 className="font-semibold text-slate-900 flex items-center gap-2 mt-4">
                <Bone size={16} className="text-slate-500"/> X-Ray Attenuation
              </h3>
              <p className="mt-1">
                X-rays are electromagnetic waves with high energy. As they pass through matter, they are absorbed and scattered. Dense materials (like calcium in bone) have higher attenuation coefficients (μ).
              </p>
              <p className="mt-2 font-mono text-xs bg-slate-100 p-2 rounded">I = I₀ e^(-μx)</p>
            </section>
          </div>
        </div>

        <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-5 flex flex-col gap-6 overflow-y-auto">
          <div className="bg-slate-100 p-4 rounded-xl border border-slate-200">
            <div className="flex justify-between items-center mb-2">
              <h3 className="font-bold text-slate-800">Ultrasound Sonography</h3>
              <button 
                onClick={triggerPulse} disabled={pulseActive}
                className="bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white px-3 py-1 rounded text-sm font-medium transition-colors"
              >
                Send Pulse
              </button>
            </div>
            <label className="text-xs font-semibold text-slate-600 block mb-1">
              Organ Boundary Depth: {tissueDepth} cm
            </label>
            <input 
              type="range" min="2" max="12" value={tissueDepth} 
              onChange={(e) => setTissueDepth(Number(e.target.value))}
              disabled={pulseActive}
              className="w-full mb-4 accent-cyan-600"
            />
            
            <div className="h-48 bg-slate-900 rounded-lg relative overflow-hidden flex flex-col">
              <div className="h-4 w-full bg-slate-400 absolute top-0 z-10 flex items-center justify-center text-[10px] text-slate-900 font-bold">Transducer</div>
              
              <div className="flex-1 w-full flex flex-col relative pt-4">
                <div className="absolute w-full bg-pink-900/30" style={{ height: `${tissueDepth * 20}px` }}></div>
                <div className="absolute w-full bg-red-900/40 border-t-2 border-slate-400" style={{ top: `${(tissueDepth * 20) + 16}px`, height: '100%' }}></div>
                
                {pulseActive && (
                  <div 
                    className="absolute w-full h-2 bg-cyan-400 shadow-[0_0_10px_cyan]"
                    style={{ top: `${renderPulsePos + 16}px` }}
                  ></div>
                )}
              </div>
            </div>
            
            <div className="mt-3 bg-slate-800 text-cyan-400 font-mono text-sm p-2 rounded text-center">
              Echo Return Time: {echoTime > 0 ? `${echoTime} µs` : '---'}
            </div>
          </div>

          <div className="bg-slate-100 p-4 rounded-xl border border-slate-200">
            <h3 className="font-bold text-slate-800 mb-2">X-Ray Transmission</h3>
            
            <div className="flex gap-4 mb-4">
              <div className="flex-1">
                <label className="text-xs text-slate-600 block">Muscle Thickness (cm): {muscleThickness}</label>
                <input type="range" min="1" max="20" value={muscleThickness} onChange={e=>setMuscleThickness(Number(e.target.value))} className="w-full accent-red-400" />
              </div>
              <div className="flex-1">
                <label className="text-xs text-slate-600 block">Bone Thickness (cm): {boneThickness}</label>
                <input type="range" min="0" max="10" value={boneThickness} onChange={e=>setBoneThickness(Number(e.target.value))} className="w-full accent-slate-400" />
              </div>
            </div>
            
            <div className="flex items-center gap-4">
              <div className="w-16 h-16 bg-white border border-slate-300 flex items-center justify-center font-bold">
                I₀
                <br/>100%
              </div>
              <div className="flex-1 h-12 relative flex">
                <div className="h-full bg-red-200" style={{ flex: muscleThickness }} title="Muscle (μ=0.1)"></div>
                <div className="h-full bg-slate-300" style={{ flex: boneThickness }} title="Bone (μ=0.5)"></div>
              </div>
              <div 
                className="w-16 h-16 border border-slate-300 flex items-center justify-center font-bold text-white transition-colors duration-300"
                style={{ backgroundColor: `rgba(0,0,0,${1 - (intensity/100)})`, color: intensity > 50 ? 'black' : 'white' }}
              >
                I
                <br/>{intensity.toFixed(1)}%
              </div>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-5 overflow-y-auto">
          <h2 className="text-lg font-bold text-slate-800 mb-3 border-b pb-2">Assessments</h2>
          
          <div className="space-y-6">
            <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
              <h3 className="font-semibold text-slate-800 mb-2">Q1: Ultrasound Depth</h3>
              <p className="text-sm text-slate-600 mb-3">
                An ultrasound pulse returns after <strong>100 µs</strong> (10⁻⁴ s). If the speed of sound in tissue is 1540 m/s, how deep is the boundary? (Answer in cm)
              </p>
              <div className="flex gap-2 items-center">
                <input 
                  type="number" value={usAns} onChange={e => setUsAns(e.target.value)}
                  placeholder="e.g. 5.5" 
                  className="flex-1 border rounded px-3 py-1.5 text-sm"
                />
                <span className="text-sm text-slate-600">cm</span>
                <button onClick={checkUS} className="bg-blue-600 text-white px-3 py-1.5 rounded text-sm font-medium hover:bg-blue-700">
                  Check
                </button>
              </div>
              {usFeedback && <p className={`mt-2 text-sm font-medium ${usFeedback.includes('Correct') ? 'text-emerald-600' : 'text-red-600'}`}>{usFeedback}</p>}
            </div>

            <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
              <h3 className="font-semibold text-slate-800 mb-2">Q2: X-Ray Attenuation</h3>
              <p className="text-sm text-slate-600 mb-3">
                An X-ray beam passes through 3 cm of bone (μ = 0.5 cm⁻¹). Assuming no muscle, what percentage of the initial intensity is transmitted?
              </p>
              <div className="flex gap-2 items-center">
                <input 
                  type="number" value={xrAns} onChange={e => setXrAns(e.target.value)}
                  placeholder="e.g. 50" 
                  className="flex-1 border rounded px-3 py-1.5 text-sm"
                />
                <span className="text-sm text-slate-600">%</span>
                <button onClick={checkXR} className="bg-blue-600 text-white px-3 py-1.5 rounded text-sm font-medium hover:bg-blue-700">
                  Check
                </button>
              </div>
              {xrFeedback && <p className={`mt-2 text-sm font-medium ${xrFeedback.includes('Correct') ? 'text-emerald-600' : 'text-red-600'}`}>{xrFeedback}</p>}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
