import { useState } from 'react';
import {Zap } from 'lucide-react';
import LabHeader from './LabHeader';

interface LabProps { onExit?: () => void; }

export default function LabS8Electromagnet({ onExit }: LabProps) {
  const [isOn, setIsOn] = useState(false);
  const [clipsPickedUp, setClipsPickedUp] = useState(false);

  const togglePower = () => {
    setIsOn(!isOn);
    if (!isOn) {
      setTimeout(() => setClipsPickedUp(true), 500);
    } else {
      setClipsPickedUp(false);
    }
  };

  return (
    <div className="overflow-y-auto flex flex-col h-screen bg-slate-50 font-sans select-none">
      <LabHeader onExit={onExit} title="Act 10.1: Making an Electromagnet" subtitle="Magnetic fields generated by electric current" />

      <div className="flex-1 flex flex-col p-6 gap-6 max-w-4xl mx-auto w-full items-center justify-center">
        
        <div className="w-full bg-slate-50 rounded-3xl shadow-lg border border-slate-200 p-8 flex flex-col items-center relative overflow-hidden h-[500px]">
          
          <div className="relative w-full h-full flex flex-col items-center justify-center">
            
            {/* The Battery */}
            <div className="absolute top-10 left-20 w-32 h-16 bg-zinc-800 rounded-md border-2 border-zinc-900 flex items-center relative shadow-xl">
               <div className="absolute -left-2 w-2 h-8 bg-zinc-400 rounded-l-sm" />
               <div className="absolute -right-2 w-2 h-8 bg-amber-600 rounded-r-sm" />
               <div className="w-full text-center text-zinc-400 font-bold text-2xl tracking-widest">1.5V</div>
               <div className="absolute -top-6 left-2 font-bold text-slate-600">-</div>
               <div className="absolute -top-6 right-2 font-bold text-red-600">+</div>
            </div>

            {/* Switch */}
            <button 
              onClick={togglePower}
              className={`absolute top-10 left-64 w-16 h-12 bg-slate-200 rounded-lg border-b-4 border-slate-300 flex items-center justify-center transition-transform active:translate-y-1 ${isOn ? 'bg-red-100 border-red-300 shadow-[inset_0_5px_10px_rgba(0,0,0,0.1)] translate-y-1' : ''}`}
            >
               <div className={`w-8 h-2 rounded-full ${isOn ? 'bg-red-500 shadow-[0_0_10px_red]' : 'bg-slate-400'}`} />
            </button>
            <div className="absolute top-2 left-64 text-xs font-bold text-slate-500 uppercase">Power Switch</div>

            {/* Wires */}
            <svg className="absolute inset-0 w-full h-full pointer-events-none z-0">
               {/* Left wire to Switch */}
               <path d="M 110 70 L 250 70" fill="none" stroke="#333" strokeWidth="4" />
               {/* Switch to Nail */}
               <path d="M 320 70 C 400 70, 400 150, 450 180" fill="none" stroke="#ef4444" strokeWidth="4" />
               {/* Right wire from Battery to Nail */}
               <path d="M 210 100 C 210 150, 300 180, 350 180" fill="none" stroke="#333" strokeWidth="4" />
            </svg>

            {/* The Electromagnet (Nail + Coil) */}
            <div className="absolute top-[170px] left-1/2 -translate-x-1/2 w-48 h-8 bg-slate-300 rounded-r-full shadow-lg border-b-2 border-slate-400 z-10 flex items-center justify-center">
               {/* Nail Head */}
               <div className="absolute -left-2 w-4 h-12 bg-slate-400 rounded-sm" />
               
               {/* Coil Wraps */}
               <div className="flex gap-1">
                 {Array.from({length: 15}).map((_, i) => (
                   <div key={i} className="w-2 h-10 bg-amber-600 border-x border-amber-800 rounded-full" />
                 ))}
               </div>

               {/* Magnetic Field Visual */}
               {isOn && (
                 <div className="absolute w-[300px] h-[150px] border-4 border-cyan-400/30 rounded-[100%] animate-ping pointer-events-none" />
               )}
            </div>

            {/* Paper Clips */}
            <div className="absolute bottom-20 left-1/2 -translate-x-1/2 w-64 h-32 flex justify-center items-end gap-2 relative">
               {[1,2,3,4,5].map(i => (
                 <div 
                   key={i} 
                   className="text-3xl text-slate-500 transition-all duration-500 ease-out z-20"
                   style={{ 
                     transform: clipsPickedUp 
                       ? `translateY(-${100 + Math.random()*20}px) rotate(${Math.random() * 90 - 45}deg)` 
                       : `translateY(0) rotate(${i * 15 - 30}deg)`
                   }}
                 >
                   📎
                 </div>
               ))}
               
               {/* Bowl/Table */}
               <div className="absolute bottom-0 w-64 h-2 bg-slate-200 rounded-full" />
            </div>

          </div>

          <div className="absolute bottom-6 bg-slate-100 px-6 py-4 rounded-xl border border-slate-200 text-center max-w-lg z-30">
            <h3 className="font-bold text-slate-800 mb-1 flex items-center justify-center gap-2">
              <Zap className="w-5 h-5 text-amber-500" />
              {isOn ? 'Current Flowing!' : 'Circuit Open'}
            </h3>
            <p className="text-sm text-slate-600">
              {isOn 
                ? "The electric current traveling through the coiled wire creates a magnetic field, turning the iron nail into a temporary magnet." 
                : "When the switch is off, no current flows, and the nail loses its magnetism."}
            </p>
          </div>

        </div>
      </div>
    </div>
  );
}
